-- -------------------------------------------------------------
-- TablePlus 6.2.1(578)
--
-- https://tableplus.com/
--
-- Database: ahnaf-web
-- Generation Time: 1404-11-11 07:07:33.1980
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE TABLE `cities` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'نام شهر',
  `slug` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'نام انگلیسی شهر',
  `province_id` bigint unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cities_province_id_foreign` (`province_id`),
  CONSTRAINT `cities_province_id_foreign` FOREIGN KEY (`province_id`) REFERENCES `provinces` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1161 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `provinces` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'نام استان',
  `slug` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'نام انگلیسی استان',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `provinces_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `cities` (`id`, `name`, `slug`, `province_id`, `created_at`, `deleted_at`, `updated_at`, `latitude`, `longitude`) VALUES
(1, 'اسکو', 'اسکو', 1, NULL, NULL, NULL, NULL, NULL),
(2, 'اهر', 'اهر', 1, NULL, NULL, NULL, NULL, NULL),
(3, 'ایلخچی', 'ایلخچی', 1, NULL, NULL, NULL, NULL, NULL),
(4, 'آبش احمد', 'آبش-احمد', 1, NULL, NULL, NULL, NULL, NULL),
(5, 'آذرشهر', 'آذرشهر', 1, NULL, NULL, NULL, NULL, NULL),
(6, 'آقکند', 'آقکند', 1, NULL, NULL, NULL, NULL, NULL),
(7, 'باسمنج', 'باسمنج', 1, NULL, NULL, NULL, NULL, NULL),
(8, 'بخشایش', 'بخشایش', 1, NULL, NULL, NULL, NULL, NULL),
(9, 'بستان آباد', 'بستان-آباد', 1, NULL, NULL, NULL, NULL, NULL),
(10, 'بناب', 'بناب', 1, NULL, NULL, NULL, NULL, NULL),
(11, 'بناب جدید', 'بناب-جدید', 1, NULL, NULL, NULL, NULL, NULL),
(12, 'تبریز', 'تبریز', 1, NULL, NULL, NULL, NULL, NULL),
(13, 'ترک', 'ترک', 1, NULL, NULL, NULL, NULL, NULL),
(14, 'ترکمانچای', 'ترکمانچای', 1, NULL, NULL, NULL, NULL, NULL),
(15, 'تسوج', 'تسوج', 1, NULL, NULL, NULL, NULL, NULL),
(16, 'تیکمه داش', 'تیکمه-داش', 1, NULL, NULL, NULL, NULL, NULL),
(17, 'جلفا', 'جلفا', 1, NULL, NULL, NULL, NULL, NULL),
(18, 'خاروانا', 'خاروانا', 1, NULL, NULL, NULL, NULL, NULL),
(19, 'خامنه', 'خامنه', 1, NULL, NULL, NULL, NULL, NULL),
(20, 'خراجو', 'خراجو', 1, NULL, NULL, NULL, NULL, NULL),
(21, 'خسروشهر', 'خسروشهر', 1, NULL, NULL, NULL, NULL, NULL),
(22, 'خضرلو', 'خضرلو', 1, NULL, NULL, NULL, NULL, NULL),
(23, 'خمارلو', 'خمارلو', 1, NULL, NULL, NULL, NULL, NULL),
(24, 'خواجه', 'خواجه', 1, NULL, NULL, NULL, NULL, NULL),
(25, 'دوزدوزان', 'دوزدوزان', 1, NULL, NULL, NULL, NULL, NULL),
(26, 'زرنق', 'زرنق', 1, NULL, NULL, NULL, NULL, NULL),
(27, 'زنوز', 'زنوز', 1, NULL, NULL, NULL, NULL, NULL),
(28, 'سراب', 'سراب', 1, NULL, NULL, NULL, NULL, NULL),
(29, 'سردرود', 'سردرود', 1, NULL, NULL, NULL, NULL, NULL),
(30, 'سهند', 'سهند', 1, NULL, NULL, NULL, NULL, NULL),
(31, 'سیس', 'سیس', 1, NULL, NULL, NULL, NULL, NULL),
(32, 'سیه رود', 'سیه-رود', 1, NULL, NULL, NULL, NULL, NULL),
(33, 'شبستر', 'شبستر', 1, NULL, NULL, NULL, NULL, NULL),
(34, 'شربیان', 'شربیان', 1, NULL, NULL, NULL, NULL, NULL),
(35, 'شرفخانه', 'شرفخانه', 1, NULL, NULL, NULL, NULL, NULL),
(36, 'شندآباد', 'شندآباد', 1, NULL, NULL, NULL, NULL, NULL),
(37, 'صوفیان', 'صوفیان', 1, NULL, NULL, NULL, NULL, NULL),
(38, 'عجب شیر', 'عجب-شیر', 1, NULL, NULL, NULL, NULL, NULL),
(39, 'قره آغاج', 'قره-آغاج', 1, NULL, NULL, NULL, NULL, NULL),
(40, 'کشکسرای', 'کشکسرای', 1, NULL, NULL, NULL, NULL, NULL),
(41, 'کلوانق', 'کلوانق', 1, NULL, NULL, NULL, NULL, NULL),
(42, 'کلیبر', 'کلیبر', 1, NULL, NULL, NULL, NULL, NULL),
(43, 'کوزه کنان', 'کوزه-کنان', 1, NULL, NULL, NULL, NULL, NULL),
(44, 'گوگان', 'گوگان', 1, NULL, NULL, NULL, NULL, NULL),
(45, 'لیلان', 'لیلان', 1, NULL, NULL, NULL, NULL, NULL),
(46, 'مراغه', 'مراغه', 1, NULL, NULL, NULL, NULL, NULL),
(47, 'مرند', 'مرند', 1, NULL, NULL, NULL, NULL, NULL),
(48, 'ملکان', 'ملکان', 1, NULL, NULL, NULL, NULL, NULL),
(49, 'ملک کیان', 'ملک-کیان', 1, NULL, NULL, NULL, NULL, NULL),
(50, 'ممقان', 'ممقان', 1, NULL, NULL, NULL, NULL, NULL),
(51, 'مهربان', 'مهربان', 1, NULL, NULL, NULL, NULL, NULL),
(52, 'میانه', 'میانه', 1, NULL, NULL, NULL, NULL, NULL),
(53, 'نظرکهریزی', 'نظرکهریزی', 1, NULL, NULL, NULL, NULL, NULL),
(54, 'هادی شهر', 'هادی-شهر', 1, NULL, NULL, NULL, NULL, NULL),
(55, 'هرگلان', 'هرگلان', 1, NULL, NULL, NULL, NULL, NULL),
(56, 'هریس', 'هریس', 1, NULL, NULL, NULL, NULL, NULL),
(57, 'هشترود', 'هشترود', 1, NULL, NULL, NULL, NULL, NULL),
(58, 'هوراند', 'هوراند', 1, NULL, NULL, NULL, NULL, NULL),
(59, 'وایقان', 'وایقان', 1, NULL, NULL, NULL, NULL, NULL),
(60, 'ورزقان', 'ورزقان', 1, NULL, NULL, NULL, NULL, NULL),
(61, 'یامچی', 'یامچی', 1, NULL, NULL, NULL, NULL, NULL),
(62, 'ارومیه', 'ارومیه', 2, NULL, NULL, NULL, NULL, NULL),
(63, 'اشنویه', 'اشنویه', 2, NULL, NULL, NULL, NULL, NULL),
(64, 'ایواوغلی', 'ایواوغلی', 2, NULL, NULL, NULL, NULL, NULL),
(65, 'آواجیق', 'آواجیق', 2, NULL, NULL, NULL, NULL, NULL),
(66, 'باروق', 'باروق', 2, NULL, NULL, NULL, NULL, NULL),
(67, 'بازرگان', 'بازرگان', 2, NULL, NULL, NULL, NULL, NULL),
(68, 'بوکان', 'بوکان', 2, NULL, NULL, NULL, NULL, NULL),
(69, 'پلدشت', 'پلدشت', 2, NULL, NULL, NULL, NULL, NULL),
(70, 'پیرانشهر', 'پیرانشهر', 2, NULL, NULL, NULL, NULL, NULL),
(71, 'تازه شهر', 'تازه-شهر', 2, NULL, NULL, NULL, NULL, NULL),
(72, 'تکاب', 'تکاب', 2, NULL, NULL, NULL, NULL, NULL),
(73, 'چهاربرج', 'چهاربرج', 2, NULL, NULL, NULL, NULL, NULL),
(74, 'خوی', 'خوی', 2, NULL, NULL, NULL, NULL, NULL),
(75, 'دیزج دیز', 'دیزج-دیز', 2, NULL, NULL, NULL, NULL, NULL),
(76, 'ربط', 'ربط', 2, NULL, NULL, NULL, NULL, NULL),
(77, 'سردشت', 'آذربایجان-غربی-سردشت', 2, NULL, NULL, NULL, NULL, NULL),
(78, 'سرو', 'سرو', 2, NULL, NULL, NULL, NULL, NULL),
(79, 'سلماس', 'سلماس', 2, NULL, NULL, NULL, NULL, NULL),
(80, 'سیلوانه', 'سیلوانه', 2, NULL, NULL, NULL, NULL, NULL),
(81, 'سیمینه', 'سیمینه', 2, NULL, NULL, NULL, NULL, NULL),
(82, 'سیه چشمه', 'سیه-چشمه', 2, NULL, NULL, NULL, NULL, NULL),
(83, 'شاهین دژ', 'شاهین-دژ', 2, NULL, NULL, NULL, NULL, NULL),
(84, 'شوط', 'شوط', 2, NULL, NULL, NULL, NULL, NULL),
(85, 'فیرورق', 'فیرورق', 2, NULL, NULL, NULL, NULL, NULL),
(86, 'قره ضیاءالدین', 'قره-ضیاءالدین', 2, NULL, NULL, NULL, NULL, NULL),
(87, 'قطور', 'قطور', 2, NULL, NULL, NULL, NULL, NULL),
(88, 'قوشچی', 'قوشچی', 2, NULL, NULL, NULL, NULL, NULL),
(89, 'کشاورز', 'کشاورز', 2, NULL, NULL, NULL, NULL, NULL),
(90, 'گردکشانه', 'گردکشانه', 2, NULL, NULL, NULL, NULL, NULL),
(91, 'ماکو', 'ماکو', 2, NULL, NULL, NULL, NULL, NULL),
(92, 'محمدیار', 'محمدیار', 2, NULL, NULL, NULL, NULL, NULL),
(93, 'محمودآباد', 'آذربایجان-غربی-محمودآباد', 2, NULL, NULL, NULL, NULL, NULL),
(94, 'مهاباد', 'آذربایجان-غربی-مهاباد', 2, NULL, NULL, NULL, NULL, NULL),
(95, 'میاندوآب', 'میاندوآب', 2, NULL, NULL, NULL, NULL, NULL),
(96, 'میرآباد', 'میرآباد', 2, NULL, NULL, NULL, NULL, NULL),
(97, 'نالوس', 'نالوس', 2, NULL, NULL, NULL, NULL, NULL),
(98, 'نقده', 'نقده', 2, NULL, NULL, NULL, NULL, NULL),
(99, 'نوشین', 'نوشین', 2, NULL, NULL, NULL, NULL, NULL),
(100, 'اردبیل', 'اردبیل', 3, NULL, NULL, NULL, NULL, NULL),
(101, 'اصلاندوز', 'اصلاندوز', 3, NULL, NULL, NULL, NULL, NULL),
(102, 'آبی بیگلو', 'آبی-بیگلو', 3, NULL, NULL, NULL, NULL, NULL),
(103, 'بیله سوار', 'بیله-سوار', 3, NULL, NULL, NULL, NULL, NULL),
(104, 'پارس آباد', 'پارس-آباد', 3, NULL, NULL, NULL, NULL, NULL),
(105, 'تازه کند', 'تازه-کند', 3, NULL, NULL, NULL, NULL, NULL),
(106, 'تازه کندانگوت', 'تازه-کندانگوت', 3, NULL, NULL, NULL, NULL, NULL),
(107, 'جعفرآباد', 'جعفرآباد', 3, NULL, NULL, NULL, NULL, NULL),
(108, 'خلخال', 'خلخال', 3, NULL, NULL, NULL, NULL, NULL),
(109, 'رضی', 'رضی', 3, NULL, NULL, NULL, NULL, NULL),
(110, 'سرعین', 'سرعین', 3, NULL, NULL, NULL, NULL, NULL),
(111, 'عنبران', 'عنبران', 3, NULL, NULL, NULL, NULL, NULL),
(112, 'فخرآباد', 'فخرآباد', 3, NULL, NULL, NULL, NULL, NULL),
(113, 'کلور', 'کلور', 3, NULL, NULL, NULL, NULL, NULL),
(114, 'کوراییم', 'کوراییم', 3, NULL, NULL, NULL, NULL, NULL),
(115, 'گرمی', 'گرمی', 3, NULL, NULL, NULL, NULL, NULL),
(116, 'گیوی', 'گیوی', 3, NULL, NULL, NULL, NULL, NULL),
(117, 'لاهرود', 'لاهرود', 3, NULL, NULL, NULL, NULL, NULL),
(118, 'مشگین شهر', 'مشگین-شهر', 3, NULL, NULL, NULL, NULL, NULL),
(119, 'نمین', 'نمین', 3, NULL, NULL, NULL, NULL, NULL),
(120, 'نیر', 'اردبیل-نیر', 3, NULL, NULL, NULL, NULL, NULL),
(121, 'هشتجین', 'هشتجین', 3, NULL, NULL, NULL, NULL, NULL),
(122, 'هیر', 'هیر', 3, NULL, NULL, NULL, NULL, NULL),
(123, 'ابریشم', 'ابریشم', 4, NULL, NULL, NULL, NULL, NULL),
(124, 'ابوزیدآباد', 'ابوزیدآباد', 4, NULL, NULL, NULL, NULL, NULL),
(125, 'اردستان', 'اردستان', 4, NULL, NULL, NULL, NULL, NULL),
(126, 'اژیه', 'اژیه', 4, NULL, NULL, NULL, NULL, NULL),
(127, 'اصفهان', 'اصفهان', 4, NULL, NULL, NULL, NULL, NULL),
(128, 'افوس', 'افوس', 4, NULL, NULL, NULL, NULL, NULL),
(129, 'انارک', 'انارک', 4, NULL, NULL, NULL, NULL, NULL),
(130, 'ایمانشهر', 'ایمانشهر', 4, NULL, NULL, NULL, NULL, NULL),
(131, 'آران وبیدگل', 'آران-وبیدگل', 4, NULL, NULL, NULL, NULL, NULL),
(132, 'بادرود', 'بادرود', 4, NULL, NULL, NULL, NULL, NULL),
(133, 'باغ بهادران', 'باغ-بهادران', 4, NULL, NULL, NULL, NULL, NULL),
(134, 'بافران', 'بافران', 4, NULL, NULL, NULL, NULL, NULL),
(135, 'برزک', 'برزک', 4, NULL, NULL, NULL, NULL, NULL),
(136, 'برف انبار', 'برف-انبار', 4, NULL, NULL, NULL, NULL, NULL),
(137, 'بهاران شهر', 'بهاران-شهر', 4, NULL, NULL, NULL, NULL, NULL),
(138, 'بهارستان', 'بهارستان', 4, NULL, NULL, NULL, NULL, NULL),
(139, 'بوئین و میاندشت', 'بوئین-میاندشت', 4, NULL, NULL, NULL, NULL, NULL),
(140, 'پیربکران', 'پیربکران', 4, NULL, NULL, NULL, NULL, NULL),
(141, 'تودشک', 'تودشک', 4, NULL, NULL, NULL, NULL, NULL),
(142, 'تیران', 'تیران', 4, NULL, NULL, NULL, NULL, NULL),
(143, 'جندق', 'جندق', 4, NULL, NULL, NULL, NULL, NULL),
(144, 'جوزدان', 'جوزدان', 4, NULL, NULL, NULL, NULL, NULL),
(145, 'جوشقان و کامو', 'جوشقان-کامو', 4, NULL, NULL, NULL, NULL, NULL),
(146, 'چادگان', 'چادگان', 4, NULL, NULL, NULL, NULL, NULL),
(147, 'چرمهین', 'چرمهین', 4, NULL, NULL, NULL, NULL, NULL),
(148, 'چمگردان', 'چمگردان', 4, NULL, NULL, NULL, NULL, NULL),
(149, 'حبیب آباد', 'حبیب-آباد', 4, NULL, NULL, NULL, NULL, NULL),
(150, 'حسن آباد', 'اصفهان-حسن-آباد', 4, NULL, NULL, NULL, NULL, NULL),
(151, 'حنا', 'حنا', 4, NULL, NULL, NULL, NULL, NULL),
(152, 'خالدآباد', 'خالدآباد', 4, NULL, NULL, NULL, NULL, NULL),
(153, 'خمینی شهر', 'خمینی-شهر', 4, NULL, NULL, NULL, NULL, NULL),
(154, 'خوانسار', 'خوانسار', 4, NULL, NULL, NULL, NULL, NULL),
(155, 'خور', 'اصفهان-خور', 4, NULL, NULL, NULL, NULL, NULL),
(157, 'خورزوق', 'خورزوق', 4, NULL, NULL, NULL, NULL, NULL),
(158, 'داران', 'داران', 4, NULL, NULL, NULL, NULL, NULL),
(159, 'دامنه', 'دامنه', 4, NULL, NULL, NULL, NULL, NULL),
(160, 'درچه', 'درچه', 4, NULL, NULL, NULL, NULL, NULL),
(161, 'دستگرد', 'دستگرد', 4, NULL, NULL, NULL, NULL, NULL),
(162, 'دهاقان', 'دهاقان', 4, NULL, NULL, NULL, NULL, NULL),
(163, 'دهق', 'دهق', 4, NULL, NULL, NULL, NULL, NULL),
(164, 'دولت آباد', 'اصفهان-دولت-آباد', 4, NULL, NULL, NULL, NULL, NULL),
(165, 'دیزیچه', 'دیزیچه', 4, NULL, NULL, NULL, NULL, NULL),
(166, 'رزوه', 'رزوه', 4, NULL, NULL, NULL, NULL, NULL),
(167, 'رضوانشهر', 'اصفهان-رضوانشهر', 4, NULL, NULL, NULL, NULL, NULL),
(168, 'زاینده رود', 'زاینده-رود', 4, NULL, NULL, NULL, NULL, NULL),
(169, 'زرین شهر', 'زرین-شهر', 4, NULL, NULL, NULL, NULL, NULL),
(170, 'زواره', 'زواره', 4, NULL, NULL, NULL, NULL, NULL),
(171, 'زیباشهر', 'زیباشهر', 4, NULL, NULL, NULL, NULL, NULL),
(172, 'سده لنجان', 'سده-لنجان', 4, NULL, NULL, NULL, NULL, NULL),
(173, 'سفیدشهر', 'سفیدشهر', 4, NULL, NULL, NULL, NULL, NULL),
(174, 'سگزی', 'سگزی', 4, NULL, NULL, NULL, NULL, NULL),
(175, 'سمیرم', 'سمیرم', 4, NULL, NULL, NULL, NULL, NULL),
(176, 'شاهین شهر', 'شاهین-شهر', 4, NULL, NULL, NULL, NULL, NULL),
(177, 'شهرضا', 'شهرضا', 4, NULL, NULL, NULL, NULL, NULL),
(178, 'طالخونچه', 'طالخونچه', 4, NULL, NULL, NULL, NULL, NULL),
(179, 'عسگران', 'عسگران', 4, NULL, NULL, NULL, NULL, NULL),
(180, 'علویجه', 'علویجه', 4, NULL, NULL, NULL, NULL, NULL),
(181, 'فرخی', 'فرخی', 4, NULL, NULL, NULL, NULL, NULL),
(182, 'فریدونشهر', 'فریدونشهر', 4, NULL, NULL, NULL, NULL, NULL),
(183, 'فلاورجان', 'فلاورجان', 4, NULL, NULL, NULL, NULL, NULL),
(184, 'فولادشهر', 'فولادشهر', 4, NULL, NULL, NULL, NULL, NULL),
(185, 'قمصر', 'قمصر', 4, NULL, NULL, NULL, NULL, NULL),
(186, 'قهجاورستان', 'قهجاورستان', 4, NULL, NULL, NULL, NULL, NULL),
(187, 'قهدریجان', 'قهدریجان', 4, NULL, NULL, NULL, NULL, NULL),
(188, 'کاشان', 'کاشان', 4, NULL, NULL, NULL, NULL, NULL),
(189, 'کرکوند', 'کرکوند', 4, NULL, NULL, NULL, NULL, NULL),
(190, 'کلیشاد و سودرجان', 'کلیشاد-سودرجان', 4, NULL, NULL, NULL, NULL, NULL),
(191, 'کمشچه', 'کمشچه', 4, NULL, NULL, NULL, NULL, NULL),
(192, 'کمه', 'کمه', 4, NULL, NULL, NULL, NULL, NULL),
(193, 'کهریزسنگ', 'کهریزسنگ', 4, NULL, NULL, NULL, NULL, NULL),
(194, 'کوشک', 'کوشک', 4, NULL, NULL, NULL, NULL, NULL),
(195, 'کوهپایه', 'کوهپایه', 4, NULL, NULL, NULL, NULL, NULL),
(196, 'گرگاب', 'گرگاب', 4, NULL, NULL, NULL, NULL, NULL),
(197, 'گزبرخوار', 'گزبرخوار', 4, NULL, NULL, NULL, NULL, NULL),
(198, 'گلپایگان', 'گلپایگان', 4, NULL, NULL, NULL, NULL, NULL),
(199, 'گلدشت', 'گلدشت', 4, NULL, NULL, NULL, NULL, NULL),
(200, 'گلشهر', 'گلشهر', 4, NULL, NULL, NULL, NULL, NULL),
(201, 'گوگد', 'گوگد', 4, NULL, NULL, NULL, NULL, NULL),
(202, 'لای بید', 'لای-بید', 4, NULL, NULL, NULL, NULL, NULL),
(203, 'مبارکه', 'مبارکه', 4, NULL, NULL, NULL, NULL, NULL),
(204, 'مجلسی', 'مجلسی', 4, NULL, NULL, NULL, NULL, NULL),
(205, 'محمدآباد', 'اصفهان-محمدآباد', 4, NULL, NULL, NULL, NULL, NULL),
(206, 'مشکات', 'مشکات', 4, NULL, NULL, NULL, NULL, NULL),
(207, 'منظریه', 'منظریه', 4, NULL, NULL, NULL, NULL, NULL),
(208, 'مهاباد', 'اصفهان-مهاباد', 4, NULL, NULL, NULL, NULL, NULL),
(209, 'میمه', 'اصفهان-میمه', 4, NULL, NULL, NULL, NULL, NULL),
(210, 'نائین', 'نائین', 4, NULL, NULL, NULL, NULL, NULL),
(211, 'نجف آباد', 'نجف-آباد', 4, NULL, NULL, NULL, NULL, NULL),
(212, 'نصرآباد', 'اصفهان-نصرآباد', 4, NULL, NULL, NULL, NULL, NULL),
(213, 'نطنز', 'نطنز', 4, NULL, NULL, NULL, NULL, NULL),
(214, 'نوش آباد', 'نوش-آباد', 4, NULL, NULL, NULL, NULL, NULL),
(215, 'نیاسر', 'نیاسر', 4, NULL, NULL, NULL, NULL, NULL),
(216, 'نیک آباد', 'نیک-آباد', 4, NULL, NULL, NULL, NULL, NULL),
(217, 'هرند', 'هرند', 4, NULL, NULL, NULL, NULL, NULL),
(218, 'ورزنه', 'ورزنه', 4, NULL, NULL, NULL, NULL, NULL),
(219, 'ورنامخواست', 'ورنامخواست', 4, NULL, NULL, NULL, NULL, NULL),
(220, 'وزوان', 'وزوان', 4, NULL, NULL, NULL, NULL, NULL),
(221, 'ونک', 'ونک', 4, NULL, NULL, NULL, NULL, NULL),
(222, 'اسارا', 'اسارا', 5, NULL, NULL, NULL, NULL, NULL),
(223, 'اشتهارد', 'اشتهارد', 5, NULL, NULL, NULL, NULL, NULL),
(224, 'تنکمان', 'تنکمان', 5, NULL, NULL, NULL, NULL, NULL),
(225, 'چهارباغ', 'چهارباغ', 5, NULL, NULL, NULL, NULL, NULL),
(226, 'سعید آباد', 'سعید-آباد', 5, NULL, NULL, NULL, NULL, NULL),
(227, 'شهر جدید هشتگرد', 'شهر-جدید-هشتگرد', 5, NULL, NULL, NULL, NULL, NULL),
(228, 'طالقان', 'طالقان', 5, NULL, NULL, NULL, NULL, NULL),
(229, 'کرج', 'کرج', 5, NULL, NULL, NULL, NULL, NULL),
(230, 'کمال شهر', 'کمال-شهر', 5, NULL, NULL, NULL, NULL, NULL),
(231, 'کوهسار', 'کوهسار', 5, NULL, NULL, NULL, NULL, NULL),
(232, 'گرمدره', 'گرمدره', 5, NULL, NULL, NULL, NULL, NULL),
(233, 'ماهدشت', 'ماهدشت', 5, NULL, NULL, NULL, NULL, NULL),
(234, 'محمدشهر', 'البرز-محمدشهر', 5, NULL, NULL, NULL, NULL, NULL),
(235, 'مشکین دشت', 'مشکین-دشت', 5, NULL, NULL, NULL, NULL, NULL),
(236, 'نظرآباد', 'نظرآباد', 5, NULL, NULL, NULL, NULL, NULL),
(237, 'هشتگرد', 'هشتگرد', 5, NULL, NULL, NULL, NULL, NULL),
(238, 'ارکواز', 'ارکواز', 6, NULL, NULL, NULL, NULL, NULL),
(239, 'ایلام', 'ایلام', 6, NULL, NULL, NULL, NULL, NULL),
(240, 'ایوان', 'ایوان', 6, NULL, NULL, NULL, NULL, NULL),
(241, 'آبدانان', 'آبدانان', 6, NULL, NULL, NULL, NULL, NULL),
(242, 'آسمان آباد', 'آسمان-آباد', 6, NULL, NULL, NULL, NULL, NULL),
(243, 'بدره', 'بدره', 6, NULL, NULL, NULL, NULL, NULL),
(244, 'پهله', 'پهله', 6, NULL, NULL, NULL, NULL, NULL),
(245, 'توحید', 'توحید', 6, NULL, NULL, NULL, NULL, NULL),
(246, 'چوار', 'چوار', 6, NULL, NULL, NULL, NULL, NULL),
(247, 'دره شهر', 'دره-شهر', 6, NULL, NULL, NULL, NULL, NULL),
(248, 'دلگشا', 'دلگشا', 6, NULL, NULL, NULL, NULL, NULL),
(249, 'دهلران', 'دهلران', 6, NULL, NULL, NULL, NULL, NULL),
(250, 'زرنه', 'زرنه', 6, NULL, NULL, NULL, NULL, NULL),
(251, 'سراب باغ', 'سراب-باغ', 6, NULL, NULL, NULL, NULL, NULL),
(252, 'سرابله', 'سرابله', 6, NULL, NULL, NULL, NULL, NULL),
(253, 'صالح آباد', 'ایلام-صالح-آباد', 6, NULL, NULL, NULL, NULL, NULL),
(254, 'لومار', 'لومار', 6, NULL, NULL, NULL, NULL, NULL),
(255, 'مهران', 'مهران', 6, NULL, NULL, NULL, NULL, NULL),
(256, 'مورموری', 'مورموری', 6, NULL, NULL, NULL, NULL, NULL),
(257, 'موسیان', 'موسیان', 6, NULL, NULL, NULL, NULL, NULL),
(258, 'میمه', 'ایلام-میمه', 6, NULL, NULL, NULL, NULL, NULL),
(259, 'امام حسن', 'امام-حسن', 7, NULL, NULL, NULL, NULL, NULL),
(260, 'انارستان', 'انارستان', 7, NULL, NULL, NULL, NULL, NULL),
(261, 'اهرم', 'اهرم', 7, NULL, NULL, NULL, NULL, NULL),
(262, 'آب پخش', 'آب-پخش', 7, NULL, NULL, NULL, NULL, NULL),
(263, 'آبدان', 'آبدان', 7, NULL, NULL, NULL, NULL, NULL),
(264, 'برازجان', 'برازجان', 7, NULL, NULL, NULL, NULL, NULL),
(265, 'بردخون', 'بردخون', 7, NULL, NULL, NULL, NULL, NULL),
(266, 'بندردیر', 'بندردیر', 7, NULL, NULL, NULL, NULL, NULL),
(267, 'بندردیلم', 'بندردیلم', 7, NULL, NULL, NULL, NULL, NULL),
(268, 'بندرریگ', 'بندرریگ', 7, NULL, NULL, NULL, NULL, NULL),
(269, 'بندرکنگان', 'بندرکنگان', 7, NULL, NULL, NULL, NULL, NULL),
(270, 'بندرگناوه', 'بندرگناوه', 7, NULL, NULL, NULL, NULL, NULL),
(271, 'بنک', 'بنک', 7, NULL, NULL, NULL, NULL, NULL),
(272, 'بوشهر', 'بوشهر', 7, NULL, NULL, NULL, NULL, NULL),
(273, 'تنگ ارم', 'تنگ-ارم', 7, NULL, NULL, NULL, NULL, NULL),
(274, 'جم', 'جم', 7, NULL, NULL, NULL, NULL, NULL),
(275, 'چغادک', 'چغادک', 7, NULL, NULL, NULL, NULL, NULL),
(276, 'خارک', 'خارک', 7, NULL, NULL, NULL, NULL, NULL),
(277, 'خورموج', 'خورموج', 7, NULL, NULL, NULL, NULL, NULL),
(278, 'دالکی', 'دالکی', 7, NULL, NULL, NULL, NULL, NULL),
(279, 'دلوار', 'دلوار', 7, NULL, NULL, NULL, NULL, NULL),
(280, 'ریز', 'ریز', 7, NULL, NULL, NULL, NULL, NULL),
(281, 'سعدآباد', 'سعدآباد', 7, NULL, NULL, NULL, NULL, NULL),
(282, 'سیراف', 'سیراف', 7, NULL, NULL, NULL, NULL, NULL),
(283, 'شبانکاره', 'شبانکاره', 7, NULL, NULL, NULL, NULL, NULL),
(284, 'شنبه', 'شنبه', 7, NULL, NULL, NULL, NULL, NULL),
(285, 'عسلویه', 'عسلویه', 7, NULL, NULL, NULL, NULL, NULL),
(286, 'کاکی', 'کاکی', 7, NULL, NULL, NULL, NULL, NULL),
(287, 'کلمه', 'کلمه', 7, NULL, NULL, NULL, NULL, NULL),
(288, 'نخل تقی', 'نخل-تقی', 7, NULL, NULL, NULL, NULL, NULL),
(289, 'وحدتیه', 'وحدتیه', 7, NULL, NULL, NULL, NULL, NULL),
(290, 'ارجمند', 'ارجمند', 8, NULL, NULL, NULL, NULL, NULL),
(291, 'اسلامشهر', 'اسلامشهر', 8, NULL, NULL, NULL, NULL, NULL),
(292, 'اندیشه', 'اندیشه', 8, NULL, NULL, NULL, NULL, NULL),
(293, 'آبسرد', 'آبسرد', 8, NULL, NULL, NULL, NULL, NULL),
(294, 'آبعلی', 'آبعلی', 8, NULL, NULL, NULL, NULL, NULL),
(295, 'باغستان', 'باغستان', 8, NULL, NULL, NULL, NULL, NULL),
(296, 'باقرشهر', 'باقرشهر', 8, NULL, NULL, NULL, NULL, NULL),
(297, 'بومهن', 'بومهن', 8, NULL, NULL, NULL, NULL, NULL),
(298, 'پاکدشت', 'پاکدشت', 8, NULL, NULL, NULL, NULL, NULL),
(299, 'پردیس', 'پردیس', 8, NULL, NULL, NULL, NULL, NULL),
(300, 'پیشوا', 'پیشوا', 8, NULL, NULL, NULL, NULL, NULL),
(301, 'تهران', 'تهران', 8, NULL, NULL, NULL, NULL, NULL),
(302, 'جوادآباد', 'جوادآباد', 8, NULL, NULL, NULL, NULL, NULL),
(303, 'چهاردانگه', 'چهاردانگه', 8, NULL, NULL, NULL, NULL, NULL),
(304, 'حسن آباد', 'تهران-حسن-آباد', 8, NULL, NULL, NULL, NULL, NULL),
(305, 'دماوند', 'دماوند', 8, NULL, NULL, NULL, NULL, NULL),
(306, 'دیزین', 'دیزین', 8, NULL, NULL, NULL, NULL, NULL),
(307, 'شهر ری', 'شهر-ری', 8, NULL, NULL, NULL, NULL, NULL),
(308, 'رباط کریم', 'رباط-کریم', 8, NULL, NULL, NULL, NULL, NULL),
(309, 'رودهن', 'رودهن', 8, NULL, NULL, NULL, NULL, NULL),
(310, 'شاهدشهر', 'شاهدشهر', 8, NULL, NULL, NULL, NULL, NULL),
(311, 'شریف آباد', 'شریف-آباد', 8, NULL, NULL, NULL, NULL, NULL),
(312, 'شمشک', 'شمشک', 8, NULL, NULL, NULL, NULL, NULL),
(313, 'شهریار', 'شهریار', 8, NULL, NULL, NULL, NULL, NULL),
(314, 'صالح آباد', 'تهران-صالح-آباد', 8, NULL, NULL, NULL, NULL, NULL),
(315, 'صباشهر', 'صباشهر', 8, NULL, NULL, NULL, NULL, NULL),
(316, 'صفادشت', 'صفادشت', 8, NULL, NULL, NULL, NULL, NULL),
(317, 'فردوسیه', 'فردوسیه', 8, NULL, NULL, NULL, NULL, NULL),
(318, 'فشم', 'فشم', 8, NULL, NULL, NULL, NULL, NULL),
(319, 'فیروزکوه', 'فیروزکوه', 8, NULL, NULL, NULL, NULL, NULL),
(320, 'قدس', 'قدس', 8, NULL, NULL, NULL, NULL, NULL),
(321, 'قرچک', 'قرچک', 8, NULL, NULL, NULL, NULL, NULL),
(322, 'کهریزک', 'کهریزک', 8, NULL, NULL, NULL, NULL, NULL),
(323, 'کیلان', 'کیلان', 8, NULL, NULL, NULL, NULL, NULL),
(324, 'گلستان', 'شهر-گلستان', 8, NULL, NULL, NULL, NULL, NULL),
(325, 'لواسان', 'لواسان', 8, NULL, NULL, NULL, NULL, NULL),
(326, 'ملارد', 'ملارد', 8, NULL, NULL, NULL, NULL, NULL),
(327, 'میگون', 'میگون', 8, NULL, NULL, NULL, NULL, NULL),
(328, 'نسیم شهر', 'نسیم-شهر', 8, NULL, NULL, NULL, NULL, NULL),
(329, 'نصیرآباد', 'نصیرآباد', 8, NULL, NULL, NULL, NULL, NULL),
(330, 'وحیدیه', 'وحیدیه', 8, NULL, NULL, NULL, NULL, NULL),
(331, 'ورامین', 'ورامین', 8, NULL, NULL, NULL, NULL, NULL),
(332, 'اردل', 'اردل', 9, NULL, NULL, NULL, NULL, NULL),
(333, 'آلونی', 'آلونی', 9, NULL, NULL, NULL, NULL, NULL),
(334, 'باباحیدر', 'باباحیدر', 9, NULL, NULL, NULL, NULL, NULL),
(335, 'بروجن', 'بروجن', 9, NULL, NULL, NULL, NULL, NULL),
(336, 'بلداجی', 'بلداجی', 9, NULL, NULL, NULL, NULL, NULL),
(337, 'بن', 'بن', 9, NULL, NULL, NULL, NULL, NULL),
(338, 'جونقان', 'جونقان', 9, NULL, NULL, NULL, NULL, NULL),
(339, 'چلگرد', 'چلگرد', 9, NULL, NULL, NULL, NULL, NULL),
(340, 'سامان', 'سامان', 9, NULL, NULL, NULL, NULL, NULL),
(341, 'سفیددشت', 'سفیددشت', 9, NULL, NULL, NULL, NULL, NULL),
(342, 'سودجان', 'سودجان', 9, NULL, NULL, NULL, NULL, NULL),
(343, 'سورشجان', 'سورشجان', 9, NULL, NULL, NULL, NULL, NULL),
(344, 'شلمزار', 'شلمزار', 9, NULL, NULL, NULL, NULL, NULL),
(345, 'شهرکرد', 'شهرکرد', 9, NULL, NULL, NULL, NULL, NULL),
(346, 'طاقانک', 'طاقانک', 9, NULL, NULL, NULL, NULL, NULL),
(347, 'فارسان', 'فارسان', 9, NULL, NULL, NULL, NULL, NULL),
(348, 'فرادنبه', 'فرادبنه', 9, NULL, NULL, NULL, NULL, NULL),
(349, 'فرخ شهر', 'فرخ-شهر', 9, NULL, NULL, NULL, NULL, NULL),
(350, 'کیان', 'کیان', 9, NULL, NULL, NULL, NULL, NULL),
(351, 'گندمان', 'گندمان', 9, NULL, NULL, NULL, NULL, NULL),
(352, 'گهرو', 'گهرو', 9, NULL, NULL, NULL, NULL, NULL),
(353, 'لردگان', 'لردگان', 9, NULL, NULL, NULL, NULL, NULL),
(354, 'مال خلیفه', 'مال-خلیفه', 9, NULL, NULL, NULL, NULL, NULL),
(355, 'ناغان', 'ناغان', 9, NULL, NULL, NULL, NULL, NULL),
(356, 'نافچ', 'نافچ', 9, NULL, NULL, NULL, NULL, NULL),
(357, 'نقنه', 'نقنه', 9, NULL, NULL, NULL, NULL, NULL),
(358, 'هفشجان', 'هفشجان', 9, NULL, NULL, NULL, NULL, NULL),
(359, 'ارسک', 'ارسک', 10, NULL, NULL, NULL, NULL, NULL),
(360, 'اسدیه', 'اسدیه', 10, NULL, NULL, NULL, NULL, NULL),
(361, 'اسفدن', 'اسفدن', 10, NULL, NULL, NULL, NULL, NULL),
(362, 'اسلامیه', 'اسلامیه', 10, NULL, NULL, NULL, NULL, NULL),
(363, 'آرین شهر', 'آرین-شهر', 10, NULL, NULL, NULL, NULL, NULL),
(364, 'آیسک', 'آیسک', 10, NULL, NULL, NULL, NULL, NULL),
(365, 'بشرویه', 'بشرویه', 10, NULL, NULL, NULL, NULL, NULL),
(366, 'بیرجند', 'بیرجند', 10, NULL, NULL, NULL, NULL, NULL),
(367, 'حاجی آباد', 'خراسان-جنوبی-حاجی-آباد', 10, NULL, NULL, NULL, NULL, NULL),
(368, 'خضری دشت بیاض', 'خضری-دشت-بیاض', 10, NULL, NULL, NULL, NULL, NULL),
(369, 'خوسف', 'خوسف', 10, NULL, NULL, NULL, NULL, NULL),
(370, 'زهان', 'زهان', 10, NULL, NULL, NULL, NULL, NULL),
(371, 'سرایان', 'سرایان', 10, NULL, NULL, NULL, NULL, NULL),
(372, 'سربیشه', 'سربیشه', 10, NULL, NULL, NULL, NULL, NULL),
(373, 'سه قلعه', 'سه-قلعه', 10, NULL, NULL, NULL, NULL, NULL),
(374, 'شوسف', 'شوسف', 10, NULL, NULL, NULL, NULL, NULL),
(375, 'طبس', 'خراسان-جنوبی-طبس-', 10, NULL, NULL, NULL, NULL, NULL),
(376, 'فردوس', 'فردوس', 10, NULL, NULL, NULL, NULL, NULL),
(377, 'قاین', 'قاین', 10, NULL, NULL, NULL, NULL, NULL),
(378, 'قهستان', 'قهستان', 10, NULL, NULL, NULL, NULL, NULL),
(379, 'محمدشهر', 'خراسان-جنوبی-محمدشهر', 10, NULL, NULL, NULL, NULL, NULL),
(380, 'مود', 'مود', 10, NULL, NULL, NULL, NULL, NULL),
(381, 'نهبندان', 'نهبندان', 10, NULL, NULL, NULL, NULL, NULL),
(382, 'نیمبلوک', 'نیمبلوک', 10, NULL, NULL, NULL, NULL, NULL),
(383, 'احمدآباد صولت', 'احمدآباد-صولت', 11, NULL, NULL, NULL, NULL, NULL),
(384, 'انابد', 'انابد', 11, NULL, NULL, NULL, NULL, NULL),
(385, 'باجگیران', 'باجگیران', 11, NULL, NULL, NULL, NULL, NULL),
(386, 'باخرز', 'باخرز', 11, NULL, NULL, NULL, NULL, NULL),
(387, 'بار', 'بار', 11, NULL, NULL, NULL, NULL, NULL),
(388, 'بایگ', 'بایگ', 11, NULL, NULL, NULL, NULL, NULL),
(389, 'بجستان', 'بجستان', 11, NULL, NULL, NULL, NULL, NULL),
(390, 'بردسکن', 'بردسکن', 11, NULL, NULL, NULL, NULL, NULL),
(391, 'بیدخت', 'بیدخت', 11, NULL, NULL, NULL, NULL, NULL),
(392, 'تایباد', 'تایباد', 11, NULL, NULL, NULL, NULL, NULL),
(393, 'تربت جام', 'تربت-جام', 11, NULL, NULL, NULL, NULL, NULL),
(394, 'تربت حیدریه', 'تربت-حیدریه', 11, NULL, NULL, NULL, NULL, NULL),
(395, 'جغتای', 'جغتای', 11, NULL, NULL, NULL, NULL, NULL),
(396, 'جنگل', 'جنگل', 11, NULL, NULL, NULL, NULL, NULL),
(397, 'چاپشلو', 'چاپشلو', 11, NULL, NULL, NULL, NULL, NULL),
(398, 'چکنه', 'چکنه', 11, NULL, NULL, NULL, NULL, NULL),
(399, 'چناران', 'چناران', 11, NULL, NULL, NULL, NULL, NULL),
(400, 'خرو', 'خرو', 11, NULL, NULL, NULL, NULL, NULL),
(401, 'خلیل آباد', 'خلیل-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(402, 'خواف', 'خواف', 11, NULL, NULL, NULL, NULL, NULL),
(403, 'داورزن', 'داورزن', 11, NULL, NULL, NULL, NULL, NULL),
(404, 'درگز', 'درگز', 11, NULL, NULL, NULL, NULL, NULL),
(405, 'در رود', 'در-رود', 11, NULL, NULL, NULL, NULL, NULL),
(406, 'دولت آباد', 'خراسان-رضوی-دولت-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(407, 'رباط سنگ', 'رباط-سنگ', 11, NULL, NULL, NULL, NULL, NULL),
(408, 'رشتخوار', 'رشتخوار', 11, NULL, NULL, NULL, NULL, NULL),
(409, 'رضویه', 'رضویه', 11, NULL, NULL, NULL, NULL, NULL),
(410, 'روداب', 'روداب', 11, NULL, NULL, NULL, NULL, NULL),
(411, 'ریوش', 'ریوش', 11, NULL, NULL, NULL, NULL, NULL),
(412, 'سبزوار', 'سبزوار', 11, NULL, NULL, NULL, NULL, NULL),
(413, 'سرخس', 'سرخس', 11, NULL, NULL, NULL, NULL, NULL),
(414, 'سفیدسنگ', 'سفیدسنگ', 11, NULL, NULL, NULL, NULL, NULL),
(415, 'سلامی', 'سلامی', 11, NULL, NULL, NULL, NULL, NULL),
(416, 'سلطان آباد', 'سلطان-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(417, 'سنگان', 'سنگان', 11, NULL, NULL, NULL, NULL, NULL),
(418, 'شادمهر', 'شادمهر', 11, NULL, NULL, NULL, NULL, NULL),
(419, 'شاندیز', 'شاندیز', 11, NULL, NULL, NULL, NULL, NULL),
(420, 'ششتمد', 'ششتمد', 11, NULL, NULL, NULL, NULL, NULL),
(421, 'شهرآباد', 'شهرآباد', 11, NULL, NULL, NULL, NULL, NULL),
(422, 'شهرزو', 'شهرزو', 11, NULL, NULL, NULL, NULL, NULL),
(423, 'صالح آباد', 'خراسان-رضوی-صالح-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(424, 'طرقبه', 'طرقبه', 11, NULL, NULL, NULL, NULL, NULL),
(425, 'عشق آباد', 'خراسان-رضوی-عشق-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(426, 'فرهادگرد', 'فرهادگرد', 11, NULL, NULL, NULL, NULL, NULL),
(427, 'فریمان', 'فریمان', 11, NULL, NULL, NULL, NULL, NULL),
(428, 'فیروزه', 'فیروزه', 11, NULL, NULL, NULL, NULL, NULL),
(429, 'فیض آباد', 'فیض-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(430, 'قاسم آباد', 'قاسم-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(431, 'قدمگاه', 'قدمگاه', 11, NULL, NULL, NULL, NULL, NULL),
(432, 'قلندرآباد', 'قلندرآباد', 11, NULL, NULL, NULL, NULL, NULL),
(433, 'قوچان', 'قوچان', 11, NULL, NULL, NULL, NULL, NULL),
(434, 'کاخک', 'کاخک', 11, NULL, NULL, NULL, NULL, NULL),
(435, 'کاریز', 'کاریز', 11, NULL, NULL, NULL, NULL, NULL),
(436, 'کاشمر', 'کاشمر', 11, NULL, NULL, NULL, NULL, NULL),
(437, 'کدکن', 'کدکن', 11, NULL, NULL, NULL, NULL, NULL),
(438, 'کلات', 'کلات', 11, NULL, NULL, NULL, NULL, NULL),
(439, 'کندر', 'کندر', 11, NULL, NULL, NULL, NULL, NULL),
(440, 'گلمکان', 'گلمکان', 11, NULL, NULL, NULL, NULL, NULL),
(441, 'گناباد', 'گناباد', 11, NULL, NULL, NULL, NULL, NULL),
(442, 'لطف آباد', 'لطف-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(443, 'مزدآوند', 'مزدآوند', 11, NULL, NULL, NULL, NULL, NULL),
(444, 'مشهد', 'مشهد', 11, NULL, NULL, NULL, NULL, NULL),
(445, 'ملک آباد', 'ملک-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(446, 'نشتیفان', 'نشتیفان', 11, NULL, NULL, NULL, NULL, NULL),
(447, 'نصرآباد', 'خراسان-رضوی-نصرآباد', 11, NULL, NULL, NULL, NULL, NULL),
(448, 'نقاب', 'نقاب', 11, NULL, NULL, NULL, NULL, NULL),
(449, 'نوخندان', 'نوخندان', 11, NULL, NULL, NULL, NULL, NULL),
(450, 'نیشابور', 'نیشابور', 11, NULL, NULL, NULL, NULL, NULL),
(451, 'نیل شهر', 'نیل-شهر', 11, NULL, NULL, NULL, NULL, NULL),
(452, 'همت آباد', 'همت-آباد', 11, NULL, NULL, NULL, NULL, NULL),
(453, 'یونسی', 'یونسی', 11, NULL, NULL, NULL, NULL, NULL),
(454, 'اسفراین', 'اسفراین', 12, NULL, NULL, NULL, NULL, NULL),
(455, 'ایور', 'ایور', 12, NULL, NULL, NULL, NULL, NULL),
(456, 'آشخانه', 'آشخانه', 12, NULL, NULL, NULL, NULL, NULL),
(457, 'بجنورد', 'بجنورد', 12, NULL, NULL, NULL, NULL, NULL),
(458, 'پیش قلعه', 'پیش-قلعه', 12, NULL, NULL, NULL, NULL, NULL),
(459, 'تیتکانلو', 'تیتکانلو', 12, NULL, NULL, NULL, NULL, NULL),
(460, 'جاجرم', 'جاجرم', 12, NULL, NULL, NULL, NULL, NULL),
(461, 'حصارگرمخان', 'حصارگرمخان', 12, NULL, NULL, NULL, NULL, NULL),
(462, 'درق', 'درق', 12, NULL, NULL, NULL, NULL, NULL),
(463, 'راز', 'راز', 12, NULL, NULL, NULL, NULL, NULL),
(464, 'سنخواست', 'سنخواست', 12, NULL, NULL, NULL, NULL, NULL),
(465, 'شوقان', 'شوقان', 12, NULL, NULL, NULL, NULL, NULL),
(466, 'شیروان', 'شیروان', 12, NULL, NULL, NULL, NULL, NULL),
(467, 'صفی آباد', 'خراسان-شمالی-صفی-آباد', 12, NULL, NULL, NULL, NULL, NULL),
(468, 'فاروج', 'فاروج', 12, NULL, NULL, NULL, NULL, NULL),
(469, 'قاضی', 'قاضی', 12, NULL, NULL, NULL, NULL, NULL),
(470, 'گرمه', 'گرمه', 12, NULL, NULL, NULL, NULL, NULL),
(471, 'لوجلی', 'لوجلی', 12, NULL, NULL, NULL, NULL, NULL),
(472, 'اروندکنار', 'اروندکنار', 13, NULL, NULL, NULL, NULL, NULL),
(473, 'الوان', 'الوان', 13, NULL, NULL, NULL, NULL, NULL),
(474, 'امیدیه', 'امیدیه', 13, NULL, NULL, NULL, NULL, NULL),
(475, 'اندیمشک', 'اندیمشک', 13, NULL, NULL, NULL, NULL, NULL),
(476, 'اهواز', 'اهواز', 13, NULL, NULL, NULL, NULL, NULL),
(477, 'ایذه', 'ایذه', 13, NULL, NULL, NULL, NULL, NULL),
(478, 'آبادان', 'آبادان', 13, NULL, NULL, NULL, NULL, NULL),
(479, 'آغاجاری', 'آغاجاری', 13, NULL, NULL, NULL, NULL, NULL),
(480, 'باغ ملک', 'باغ-ملک', 13, NULL, NULL, NULL, NULL, NULL),
(481, 'بستان', 'بستان', 13, NULL, NULL, NULL, NULL, NULL),
(482, 'بندرامام خمینی', 'بندرامام-خمینی', 13, NULL, NULL, NULL, NULL, NULL),
(483, 'بندرماهشهر', 'بندرماهشهر', 13, NULL, NULL, NULL, NULL, NULL),
(484, 'بهبهان', 'بهبهان', 13, NULL, NULL, NULL, NULL, NULL),
(485, 'ترکالکی', 'ترکالکی', 13, NULL, NULL, NULL, NULL, NULL),
(486, 'جایزان', 'جایزان', 13, NULL, NULL, NULL, NULL, NULL),
(487, 'چمران', 'چمران', 13, NULL, NULL, NULL, NULL, NULL),
(488, 'چویبده', 'چویبده', 13, NULL, NULL, NULL, NULL, NULL),
(489, 'حر', 'حر', 13, NULL, NULL, NULL, NULL, NULL),
(490, 'حسینیه', 'حسینیه', 13, NULL, NULL, NULL, NULL, NULL),
(491, 'حمزه', 'حمزه', 13, NULL, NULL, NULL, NULL, NULL),
(492, 'حمیدیه', 'حمیدیه', 13, NULL, NULL, NULL, NULL, NULL),
(493, 'خرمشهر', 'خرمشهر', 13, NULL, NULL, NULL, NULL, NULL),
(494, 'دارخوین', 'دارخوین', 13, NULL, NULL, NULL, NULL, NULL),
(495, 'دزآب', 'دزآب', 13, NULL, NULL, NULL, NULL, NULL),
(496, 'دزفول', 'دزفول', 13, NULL, NULL, NULL, NULL, NULL),
(497, 'دهدز', 'دهدز', 13, NULL, NULL, NULL, NULL, NULL),
(498, 'رامشیر', 'رامشیر', 13, NULL, NULL, NULL, NULL, NULL),
(499, 'رامهرمز', 'رامهرمز', 13, NULL, NULL, NULL, NULL, NULL),
(500, 'رفیع', 'رفیع', 13, NULL, NULL, NULL, NULL, NULL),
(501, 'زهره', 'زهره', 13, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `cities` (`id`, `name`, `slug`, `province_id`, `created_at`, `deleted_at`, `updated_at`, `latitude`, `longitude`) VALUES
(502, 'سالند', 'سالند', 13, NULL, NULL, NULL, NULL, NULL),
(503, 'سردشت', 'خوزستان-سردشت', 13, NULL, NULL, NULL, NULL, NULL),
(504, 'سوسنگرد', 'سوسنگرد', 13, NULL, NULL, NULL, NULL, NULL),
(505, 'شادگان', 'شادگان', 13, NULL, NULL, NULL, NULL, NULL),
(506, 'شاوور', 'شاوور', 13, NULL, NULL, NULL, NULL, NULL),
(507, 'شرافت', 'شرافت', 13, NULL, NULL, NULL, NULL, NULL),
(508, 'شوش', 'شوش', 13, NULL, NULL, NULL, NULL, NULL),
(509, 'شوشتر', 'شوشتر', 13, NULL, NULL, NULL, NULL, NULL),
(510, 'شیبان', 'شیبان', 13, NULL, NULL, NULL, NULL, NULL),
(511, 'صالح شهر', 'صالح-شهر', 13, NULL, NULL, NULL, NULL, NULL),
(512, 'صفی آباد', 'خوزستان-صفی-آباد', 13, NULL, NULL, NULL, NULL, NULL),
(513, 'صیدون', 'صیدون', 13, NULL, NULL, NULL, NULL, NULL),
(514, 'قلعه تل', 'قلعه-تل', 13, NULL, NULL, NULL, NULL, NULL),
(515, 'قلعه خواجه', 'قلعه-خواجه', 13, NULL, NULL, NULL, NULL, NULL),
(516, 'گتوند', 'گتوند', 13, NULL, NULL, NULL, NULL, NULL),
(517, 'لالی', 'لالی', 13, NULL, NULL, NULL, NULL, NULL),
(518, 'مسجدسلیمان', 'مسجدسلیمان', 13, NULL, NULL, NULL, NULL, NULL),
(520, 'ملاثانی', 'ملاثانی', 13, NULL, NULL, NULL, NULL, NULL),
(521, 'میانرود', 'میانرود', 13, NULL, NULL, NULL, NULL, NULL),
(522, 'مینوشهر', 'مینوشهر', 13, NULL, NULL, NULL, NULL, NULL),
(523, 'هفتگل', 'هفتگل', 13, NULL, NULL, NULL, NULL, NULL),
(524, 'هندیجان', 'هندیجان', 13, NULL, NULL, NULL, NULL, NULL),
(525, 'هویزه', 'هویزه', 13, NULL, NULL, NULL, NULL, NULL),
(526, 'ویس', 'ویس', 13, NULL, NULL, NULL, NULL, NULL),
(527, 'ابهر', 'ابهر', 14, NULL, NULL, NULL, NULL, NULL),
(528, 'ارمغان خانه', 'ارمغان-خانه', 14, NULL, NULL, NULL, NULL, NULL),
(529, 'آب بر', 'آب-بر', 14, NULL, NULL, NULL, NULL, NULL),
(530, 'چورزق', 'چورزق', 14, NULL, NULL, NULL, NULL, NULL),
(531, 'حلب', 'حلب', 14, NULL, NULL, NULL, NULL, NULL),
(532, 'خرمدره', 'خرمدره', 14, NULL, NULL, NULL, NULL, NULL),
(533, 'دندی', 'دندی', 14, NULL, NULL, NULL, NULL, NULL),
(534, 'زرین آباد', 'زرین-آباد', 14, NULL, NULL, NULL, NULL, NULL),
(535, 'زرین رود', 'زرین-رود', 14, NULL, NULL, NULL, NULL, NULL),
(536, 'زنجان', 'زنجان', 14, NULL, NULL, NULL, NULL, NULL),
(537, 'سجاس', 'سجاس', 14, NULL, NULL, NULL, NULL, NULL),
(538, 'سلطانیه', 'سلطانیه', 14, NULL, NULL, NULL, NULL, NULL),
(539, 'سهرورد', 'سهرورد', 14, NULL, NULL, NULL, NULL, NULL),
(540, 'صائین قلعه', 'صائین-قلعه', 14, NULL, NULL, NULL, NULL, NULL),
(541, 'قیدار', 'قیدار', 14, NULL, NULL, NULL, NULL, NULL),
(542, 'گرماب', 'گرماب', 14, NULL, NULL, NULL, NULL, NULL),
(543, 'ماه نشان', 'ماه-نشان', 14, NULL, NULL, NULL, NULL, NULL),
(544, 'هیدج', 'هیدج', 14, NULL, NULL, NULL, NULL, NULL),
(545, 'امیریه', 'امیریه', 15, NULL, NULL, NULL, NULL, NULL),
(546, 'ایوانکی', 'ایوانکی', 15, NULL, NULL, NULL, NULL, NULL),
(547, 'آرادان', 'آرادان', 15, NULL, NULL, NULL, NULL, NULL),
(548, 'بسطام', 'بسطام', 15, NULL, NULL, NULL, NULL, NULL),
(549, 'بیارجمند', 'بیارجمند', 15, NULL, NULL, NULL, NULL, NULL),
(550, 'دامغان', 'دامغان', 15, NULL, NULL, NULL, NULL, NULL),
(551, 'درجزین', 'درجزین', 15, NULL, NULL, NULL, NULL, NULL),
(552, 'دیباج', 'دیباج', 15, NULL, NULL, NULL, NULL, NULL),
(553, 'سرخه', 'سرخه', 15, NULL, NULL, NULL, NULL, NULL),
(554, 'سمنان', 'سمنان', 15, NULL, NULL, NULL, NULL, NULL),
(555, 'شاهرود', 'شاهرود', 15, NULL, NULL, NULL, NULL, NULL),
(556, 'شهمیرزاد', 'شهمیرزاد', 15, NULL, NULL, NULL, NULL, NULL),
(557, 'کلاته خیج', 'کلاته-خیج', 15, NULL, NULL, NULL, NULL, NULL),
(558, 'گرمسار', 'گرمسار', 15, NULL, NULL, NULL, NULL, NULL),
(559, 'مجن', 'مجن', 15, NULL, NULL, NULL, NULL, NULL),
(560, 'مهدی شهر', 'مهدی-شهر', 15, NULL, NULL, NULL, NULL, NULL),
(561, 'میامی', 'میامی', 15, NULL, NULL, NULL, NULL, NULL),
(562, 'ادیمی', 'ادیمی', 16, NULL, NULL, NULL, NULL, NULL),
(563, 'اسپکه', 'اسپکه', 16, NULL, NULL, NULL, NULL, NULL),
(564, 'ایرانشهر', 'ایرانشهر', 16, NULL, NULL, NULL, NULL, NULL),
(565, 'بزمان', 'بزمان', 16, NULL, NULL, NULL, NULL, NULL),
(566, 'بمپور', 'بمپور', 16, NULL, NULL, NULL, NULL, NULL),
(567, 'بنت', 'بنت', 16, NULL, NULL, NULL, NULL, NULL),
(568, 'بنجار', 'بنجار', 16, NULL, NULL, NULL, NULL, NULL),
(569, 'پیشین', 'پیشین', 16, NULL, NULL, NULL, NULL, NULL),
(570, 'جالق', 'جالق', 16, NULL, NULL, NULL, NULL, NULL),
(571, 'چابهار', 'چابهار', 16, NULL, NULL, NULL, NULL, NULL),
(572, 'خاش', 'خاش', 16, NULL, NULL, NULL, NULL, NULL),
(573, 'دوست محمد', 'دوست-محمد', 16, NULL, NULL, NULL, NULL, NULL),
(574, 'راسک', 'راسک', 16, NULL, NULL, NULL, NULL, NULL),
(575, 'زابل', 'زابل', 16, NULL, NULL, NULL, NULL, NULL),
(576, 'زابلی', 'زابلی', 16, NULL, NULL, NULL, NULL, NULL),
(577, 'زاهدان', 'زاهدان', 16, NULL, NULL, NULL, NULL, NULL),
(578, 'زهک', 'زهک', 16, NULL, NULL, NULL, NULL, NULL),
(579, 'سراوان', 'سراوان', 16, NULL, NULL, NULL, NULL, NULL),
(580, 'سرباز', 'سرباز', 16, NULL, NULL, NULL, NULL, NULL),
(581, 'سوران', 'سوران', 16, NULL, NULL, NULL, NULL, NULL),
(582, 'سیرکان', 'سیرکان', 16, NULL, NULL, NULL, NULL, NULL),
(583, 'علی اکبر', 'علی-اکبر', 16, NULL, NULL, NULL, NULL, NULL),
(584, 'فنوج', 'فنوج', 16, NULL, NULL, NULL, NULL, NULL),
(585, 'قصرقند', 'قصرقند', 16, NULL, NULL, NULL, NULL, NULL),
(586, 'کنارک', 'کنارک', 16, NULL, NULL, NULL, NULL, NULL),
(587, 'گشت', 'گشت', 16, NULL, NULL, NULL, NULL, NULL),
(588, 'گلمورتی', 'گلمورتی', 16, NULL, NULL, NULL, NULL, NULL),
(589, 'محمدان', 'محمدان', 16, NULL, NULL, NULL, NULL, NULL),
(590, 'محمدآباد', 'سیستان-و-بلوچستان-محمدآباد', 16, NULL, NULL, NULL, NULL, NULL),
(591, 'محمدی', 'محمدی', 16, NULL, NULL, NULL, NULL, NULL),
(592, 'میرجاوه', 'میرجاوه', 16, NULL, NULL, NULL, NULL, NULL),
(593, 'نصرت آباد', 'نصرت-آباد', 16, NULL, NULL, NULL, NULL, NULL),
(594, 'نگور', 'نگور', 16, NULL, NULL, NULL, NULL, NULL),
(595, 'نوک آباد', 'نوک-آباد', 16, NULL, NULL, NULL, NULL, NULL),
(596, 'نیک شهر', 'نیک-شهر', 16, NULL, NULL, NULL, NULL, NULL),
(597, 'هیدوچ', 'هیدوچ', 16, NULL, NULL, NULL, NULL, NULL),
(598, 'اردکان', 'فارس-اردکان', 17, NULL, NULL, NULL, NULL, NULL),
(599, 'ارسنجان', 'ارسنجان', 17, NULL, NULL, NULL, NULL, NULL),
(600, 'استهبان', 'استهبان', 17, NULL, NULL, NULL, NULL, NULL),
(601, 'اشکنان', 'اشکنان', 17, NULL, NULL, NULL, NULL, NULL),
(602, 'افزر', 'افزر', 17, NULL, NULL, NULL, NULL, NULL),
(603, 'اقلید', 'اقلید', 17, NULL, NULL, NULL, NULL, NULL),
(604, 'امام شهر', 'امام-شهر', 17, NULL, NULL, NULL, NULL, NULL),
(605, 'اهل', 'اهل', 17, NULL, NULL, NULL, NULL, NULL),
(606, 'اوز', 'اوز', 17, NULL, NULL, NULL, NULL, NULL),
(607, 'ایج', 'ایج', 17, NULL, NULL, NULL, NULL, NULL),
(608, 'ایزدخواست', 'ایزدخواست', 17, NULL, NULL, NULL, NULL, NULL),
(609, 'آباده', 'آباده', 17, NULL, NULL, NULL, NULL, NULL),
(610, 'آباده طشک', 'آباده-طشک', 17, NULL, NULL, NULL, NULL, NULL),
(611, 'باب انار', 'باب-انار', 17, NULL, NULL, NULL, NULL, NULL),
(612, 'بالاده', 'فارس-بالاده', 17, NULL, NULL, NULL, NULL, NULL),
(613, 'بنارویه', 'بنارویه', 17, NULL, NULL, NULL, NULL, NULL),
(614, 'بهمن', 'بهمن', 17, NULL, NULL, NULL, NULL, NULL),
(615, 'بوانات', 'بوانات', 17, NULL, NULL, NULL, NULL, NULL),
(616, 'بیرم', 'بیرم', 17, NULL, NULL, NULL, NULL, NULL),
(617, 'بیضا', 'بیضا', 17, NULL, NULL, NULL, NULL, NULL),
(618, 'جنت شهر', 'جنت-شهر', 17, NULL, NULL, NULL, NULL, NULL),
(619, 'جهرم', 'جهرم', 17, NULL, NULL, NULL, NULL, NULL),
(620, 'جویم', 'جویم', 17, NULL, NULL, NULL, NULL, NULL),
(621, 'زرین دشت', 'زرین-دشت', 17, NULL, NULL, NULL, NULL, NULL),
(622, 'حسن آباد', 'فارس-حسن-آباد', 17, NULL, NULL, NULL, NULL, NULL),
(623, 'خان زنیان', 'خان-زنیان', 17, NULL, NULL, NULL, NULL, NULL),
(624, 'خاوران', 'خاوران', 17, NULL, NULL, NULL, NULL, NULL),
(625, 'خرامه', 'خرامه', 17, NULL, NULL, NULL, NULL, NULL),
(626, 'خشت', 'خشت', 17, NULL, NULL, NULL, NULL, NULL),
(627, 'خنج', 'خنج', 17, NULL, NULL, NULL, NULL, NULL),
(628, 'خور', 'فارس-خور', 17, NULL, NULL, NULL, NULL, NULL),
(629, 'داراب', 'داراب', 17, NULL, NULL, NULL, NULL, NULL),
(630, 'داریان', 'داریان', 17, NULL, NULL, NULL, NULL, NULL),
(631, 'دبیران', 'دبیران', 17, NULL, NULL, NULL, NULL, NULL),
(632, 'دژکرد', 'دژکرد', 17, NULL, NULL, NULL, NULL, NULL),
(633, 'دهرم', 'دهرم', 17, NULL, NULL, NULL, NULL, NULL),
(634, 'دوبرجی', 'دوبرجی', 17, NULL, NULL, NULL, NULL, NULL),
(635, 'رامجرد', 'رامجرد', 17, NULL, NULL, NULL, NULL, NULL),
(636, 'رونیز', 'رونیز', 17, NULL, NULL, NULL, NULL, NULL),
(637, 'زاهدشهر', 'زاهدشهر', 17, NULL, NULL, NULL, NULL, NULL),
(638, 'زرقان', 'زرقان', 17, NULL, NULL, NULL, NULL, NULL),
(639, 'سده', 'سده', 17, NULL, NULL, NULL, NULL, NULL),
(640, 'سروستان', 'سروستان', 17, NULL, NULL, NULL, NULL, NULL),
(641, 'سعادت شهر', 'سعادت-شهر', 17, NULL, NULL, NULL, NULL, NULL),
(642, 'سورمق', 'سورمق', 17, NULL, NULL, NULL, NULL, NULL),
(643, 'سیدان', 'سیدان', 17, NULL, NULL, NULL, NULL, NULL),
(644, 'ششده', 'ششده', 17, NULL, NULL, NULL, NULL, NULL),
(645, 'شهرپیر', 'شهرپیر', 17, NULL, NULL, NULL, NULL, NULL),
(646, 'شهرصدرا', 'شهرصدرا', 17, NULL, NULL, NULL, NULL, NULL),
(647, 'شیراز', 'شیراز', 17, NULL, NULL, NULL, NULL, NULL),
(648, 'صغاد', 'صغاد', 17, NULL, NULL, NULL, NULL, NULL),
(649, 'صفاشهر', 'صفاشهر', 17, NULL, NULL, NULL, NULL, NULL),
(650, 'علامرودشت', 'علامرودشت', 17, NULL, NULL, NULL, NULL, NULL),
(651, 'فدامی', 'فدامی', 17, NULL, NULL, NULL, NULL, NULL),
(652, 'فراشبند', 'فراشبند', 17, NULL, NULL, NULL, NULL, NULL),
(653, 'فسا', 'فسا', 17, NULL, NULL, NULL, NULL, NULL),
(654, 'فیروزآباد', 'فارس-فیروزآباد', 17, NULL, NULL, NULL, NULL, NULL),
(655, 'قائمیه', 'قائمیه', 17, NULL, NULL, NULL, NULL, NULL),
(656, 'قادرآباد', 'قادرآباد', 17, NULL, NULL, NULL, NULL, NULL),
(657, 'قطب آباد', 'قطب-آباد', 17, NULL, NULL, NULL, NULL, NULL),
(658, 'قطرویه', 'قطرویه', 17, NULL, NULL, NULL, NULL, NULL),
(659, 'قیر', 'قیر', 17, NULL, NULL, NULL, NULL, NULL),
(660, 'کارزین (فتح آباد)', 'کارزین-فتح-آباد', 17, NULL, NULL, NULL, NULL, NULL),
(661, 'کازرون', 'کازرون', 17, NULL, NULL, NULL, NULL, NULL),
(662, 'کامفیروز', 'کامفیروز', 17, NULL, NULL, NULL, NULL, NULL),
(663, 'کره ای', 'کره-ای', 17, NULL, NULL, NULL, NULL, NULL),
(664, 'کنارتخته', 'کنارتخته', 17, NULL, NULL, NULL, NULL, NULL),
(665, 'کوار', 'کوار', 17, NULL, NULL, NULL, NULL, NULL),
(666, 'گراش', 'گراش', 17, NULL, NULL, NULL, NULL, NULL),
(667, 'گله دار', 'گله-دار', 17, NULL, NULL, NULL, NULL, NULL),
(668, 'لار', 'لار', 17, NULL, NULL, NULL, NULL, NULL),
(669, 'لامرد', 'لامرد', 17, NULL, NULL, NULL, NULL, NULL),
(670, 'لپویی', 'لپویی', 17, NULL, NULL, NULL, NULL, NULL),
(671, 'لطیفی', 'لطیفی', 17, NULL, NULL, NULL, NULL, NULL),
(672, 'مبارک آباددیز', 'مبارک-آباددیز', 17, NULL, NULL, NULL, NULL, NULL),
(673, 'مرودشت', 'مرودشت', 17, NULL, NULL, NULL, NULL, NULL),
(674, 'مشکان', 'مشکان', 17, NULL, NULL, NULL, NULL, NULL),
(675, 'مصیری', 'مصیری', 17, NULL, NULL, NULL, NULL, NULL),
(676, 'مهر', 'مهر', 17, NULL, NULL, NULL, NULL, NULL),
(677, 'میمند', 'میمند', 17, NULL, NULL, NULL, NULL, NULL),
(678, 'نوبندگان', 'نوبندگان', 17, NULL, NULL, NULL, NULL, NULL),
(679, 'نوجین', 'نوجین', 17, NULL, NULL, NULL, NULL, NULL),
(680, 'نودان', 'نودان', 17, NULL, NULL, NULL, NULL, NULL),
(681, 'نورآباد', 'فارس-نورآباد', 17, NULL, NULL, NULL, NULL, NULL),
(682, 'نی ریز', 'نی-ریز', 17, NULL, NULL, NULL, NULL, NULL),
(683, 'وراوی', 'وراوی', 17, NULL, NULL, NULL, NULL, NULL),
(684, 'ارداق', 'ارداق', 18, NULL, NULL, NULL, NULL, NULL),
(685, 'اسفرورین', 'اسفرورین', 18, NULL, NULL, NULL, NULL, NULL),
(686, 'اقبالیه', 'اقبالیه', 18, NULL, NULL, NULL, NULL, NULL),
(687, 'الوند', 'الوند', 18, NULL, NULL, NULL, NULL, NULL),
(688, 'آبگرم', 'آبگرم', 18, NULL, NULL, NULL, NULL, NULL),
(689, 'آبیک', 'آبیک', 18, NULL, NULL, NULL, NULL, NULL),
(690, 'آوج', 'آوج', 18, NULL, NULL, NULL, NULL, NULL),
(691, 'بوئین زهرا', 'بوئین-زهرا', 18, NULL, NULL, NULL, NULL, NULL),
(692, 'بیدستان', 'بیدستان', 18, NULL, NULL, NULL, NULL, NULL),
(693, 'تاکستان', 'تاکستان', 18, NULL, NULL, NULL, NULL, NULL),
(694, 'خاکعلی', 'خاکعلی', 18, NULL, NULL, NULL, NULL, NULL),
(695, 'خرمدشت', 'خرمدشت', 18, NULL, NULL, NULL, NULL, NULL),
(696, 'دانسفهان', 'دانسفهان', 18, NULL, NULL, NULL, NULL, NULL),
(697, 'رازمیان', 'رازمیان', 18, NULL, NULL, NULL, NULL, NULL),
(698, 'سگزآباد', 'سگزآباد', 18, NULL, NULL, NULL, NULL, NULL),
(699, 'سیردان', 'سیردان', 18, NULL, NULL, NULL, NULL, NULL),
(700, 'شال', 'شال', 18, NULL, NULL, NULL, NULL, NULL),
(701, 'شریفیه', 'شریفیه', 18, NULL, NULL, NULL, NULL, NULL),
(702, 'ضیاآباد', 'ضیاآباد', 18, NULL, NULL, NULL, NULL, NULL),
(703, 'قزوین', 'قزوین', 18, NULL, NULL, NULL, NULL, NULL),
(704, 'کوهین', 'کوهین', 18, NULL, NULL, NULL, NULL, NULL),
(705, 'محمدیه', 'محمدیه', 18, NULL, NULL, NULL, NULL, NULL),
(706, 'محمودآباد نمونه', 'محمودآباد-نمونه', 18, NULL, NULL, NULL, NULL, NULL),
(707, 'معلم کلایه', 'معلم-کلایه', 18, NULL, NULL, NULL, NULL, NULL),
(708, 'نرجه', 'نرجه', 18, NULL, NULL, NULL, NULL, NULL),
(709, 'جعفریه', 'جعفریه', 19, NULL, NULL, NULL, NULL, NULL),
(710, 'دستجرد', 'دستجرد', 19, NULL, NULL, NULL, NULL, NULL),
(711, 'سلفچگان', 'سلفچگان', 19, NULL, NULL, NULL, NULL, NULL),
(712, 'قم', 'قم', 19, NULL, NULL, NULL, NULL, NULL),
(713, 'قنوات', 'قنوات', 19, NULL, NULL, NULL, NULL, NULL),
(714, 'کهک', 'کهک', 19, NULL, NULL, NULL, NULL, NULL),
(715, 'آرمرده', 'آرمرده', 20, NULL, NULL, NULL, NULL, NULL),
(716, 'بابارشانی', 'بابارشانی', 20, NULL, NULL, NULL, NULL, NULL),
(717, 'بانه', 'بانه', 20, NULL, NULL, NULL, NULL, NULL),
(718, 'بلبان آباد', 'بلبان-آباد', 20, NULL, NULL, NULL, NULL, NULL),
(719, 'بوئین سفلی', 'بوئین-سفلی', 20, NULL, NULL, NULL, NULL, NULL),
(720, 'بیجار', 'بیجار', 20, NULL, NULL, NULL, NULL, NULL),
(721, 'چناره', 'چناره', 20, NULL, NULL, NULL, NULL, NULL),
(722, 'دزج', 'دزج', 20, NULL, NULL, NULL, NULL, NULL),
(723, 'دلبران', 'دلبران', 20, NULL, NULL, NULL, NULL, NULL),
(724, 'دهگلان', 'دهگلان', 20, NULL, NULL, NULL, NULL, NULL),
(725, 'دیواندره', 'دیواندره', 20, NULL, NULL, NULL, NULL, NULL),
(726, 'زرینه', 'زرینه', 20, NULL, NULL, NULL, NULL, NULL),
(727, 'سروآباد', 'سروآباد', 20, NULL, NULL, NULL, NULL, NULL),
(728, 'سریش آباد', 'سریش-آباد', 20, NULL, NULL, NULL, NULL, NULL),
(729, 'سقز', 'سقز', 20, NULL, NULL, NULL, NULL, NULL),
(730, 'سنندج', 'سنندج', 20, NULL, NULL, NULL, NULL, NULL),
(731, 'شویشه', 'شویشه', 20, NULL, NULL, NULL, NULL, NULL),
(732, 'صاحب', 'صاحب', 20, NULL, NULL, NULL, NULL, NULL),
(733, 'قروه', 'قروه', 20, NULL, NULL, NULL, NULL, NULL),
(734, 'کامیاران', 'کامیاران', 20, NULL, NULL, NULL, NULL, NULL),
(735, 'کانی دینار', 'کانی-دینار', 20, NULL, NULL, NULL, NULL, NULL),
(736, 'کانی سور', 'کانی-سور', 20, NULL, NULL, NULL, NULL, NULL),
(737, 'مریوان', 'مریوان', 20, NULL, NULL, NULL, NULL, NULL),
(738, 'موچش', 'موچش', 20, NULL, NULL, NULL, NULL, NULL),
(739, 'یاسوکند', 'یاسوکند', 20, NULL, NULL, NULL, NULL, NULL),
(740, 'اختیارآباد', 'اختیارآباد', 21, NULL, NULL, NULL, NULL, NULL),
(741, 'ارزوئیه', 'ارزوئیه', 21, NULL, NULL, NULL, NULL, NULL),
(742, 'امین شهر', 'امین-شهر', 21, NULL, NULL, NULL, NULL, NULL),
(743, 'انار', 'انار', 21, NULL, NULL, NULL, NULL, NULL),
(744, 'اندوهجرد', 'اندوهجرد', 21, NULL, NULL, NULL, NULL, NULL),
(745, 'باغین', 'باغین', 21, NULL, NULL, NULL, NULL, NULL),
(746, 'بافت', 'بافت', 21, NULL, NULL, NULL, NULL, NULL),
(747, 'بردسیر', 'بردسیر', 21, NULL, NULL, NULL, NULL, NULL),
(748, 'بروات', 'بروات', 21, NULL, NULL, NULL, NULL, NULL),
(749, 'بزنجان', 'بزنجان', 21, NULL, NULL, NULL, NULL, NULL),
(750, 'بم', 'بم', 21, NULL, NULL, NULL, NULL, NULL),
(751, 'بهرمان', 'بهرمان', 21, NULL, NULL, NULL, NULL, NULL),
(752, 'پاریز', 'پاریز', 21, NULL, NULL, NULL, NULL, NULL),
(753, 'جبالبارز', 'جبالبارز', 21, NULL, NULL, NULL, NULL, NULL),
(754, 'جوپار', 'جوپار', 21, NULL, NULL, NULL, NULL, NULL),
(755, 'جوزم', 'جوزم', 21, NULL, NULL, NULL, NULL, NULL),
(756, 'جیرفت', 'جیرفت', 21, NULL, NULL, NULL, NULL, NULL),
(757, 'چترود', 'چترود', 21, NULL, NULL, NULL, NULL, NULL),
(758, 'خاتون آباد', 'خاتون-آباد', 21, NULL, NULL, NULL, NULL, NULL),
(759, 'خانوک', 'خانوک', 21, NULL, NULL, NULL, NULL, NULL),
(760, 'خورسند', 'خورسند', 21, NULL, NULL, NULL, NULL, NULL),
(761, 'درب بهشت', 'درب-بهشت', 21, NULL, NULL, NULL, NULL, NULL),
(762, 'دهج', 'دهج', 21, NULL, NULL, NULL, NULL, NULL),
(763, 'رابر', 'رابر', 21, NULL, NULL, NULL, NULL, NULL),
(764, 'راور', 'راور', 21, NULL, NULL, NULL, NULL, NULL),
(765, 'راین', 'راین', 21, NULL, NULL, NULL, NULL, NULL),
(766, 'رفسنجان', 'رفسنجان', 21, NULL, NULL, NULL, NULL, NULL),
(767, 'رودبار', 'کرمان-رودبار', 21, NULL, NULL, NULL, NULL, NULL),
(768, 'ریحان شهر', 'ریحان-شهر', 21, NULL, NULL, NULL, NULL, NULL),
(769, 'زرند', 'زرند', 21, NULL, NULL, NULL, NULL, NULL),
(770, 'زنگی آباد', 'زنگی-آباد', 21, NULL, NULL, NULL, NULL, NULL),
(771, 'زیدآباد', 'زیدآباد', 21, NULL, NULL, NULL, NULL, NULL),
(772, 'سیرجان', 'سیرجان', 21, NULL, NULL, NULL, NULL, NULL),
(773, 'شهداد', 'شهداد', 21, NULL, NULL, NULL, NULL, NULL),
(774, 'شهربابک', 'شهربابک', 21, NULL, NULL, NULL, NULL, NULL),
(775, 'صفائیه', 'صفائیه', 21, NULL, NULL, NULL, NULL, NULL),
(776, 'عنبرآباد', 'عنبرآباد', 21, NULL, NULL, NULL, NULL, NULL),
(777, 'فاریاب', 'فاریاب', 21, NULL, NULL, NULL, NULL, NULL),
(778, 'فهرج', 'فهرج', 21, NULL, NULL, NULL, NULL, NULL),
(779, 'قلعه گنج', 'قلعه-گنج', 21, NULL, NULL, NULL, NULL, NULL),
(780, 'کاظم آباد', 'کاظم-آباد', 21, NULL, NULL, NULL, NULL, NULL),
(781, 'کرمان', 'کرمان', 21, NULL, NULL, NULL, NULL, NULL),
(782, 'کشکوئیه', 'کشکوئیه', 21, NULL, NULL, NULL, NULL, NULL),
(783, 'کهنوج', 'کهنوج', 21, NULL, NULL, NULL, NULL, NULL),
(784, 'کوهبنان', 'کوهبنان', 21, NULL, NULL, NULL, NULL, NULL),
(785, 'کیانشهر', 'کیانشهر', 21, NULL, NULL, NULL, NULL, NULL),
(786, 'گلباف', 'گلباف', 21, NULL, NULL, NULL, NULL, NULL),
(787, 'گلزار', 'گلزار', 21, NULL, NULL, NULL, NULL, NULL),
(788, 'لاله زار', 'لاله-زار', 21, NULL, NULL, NULL, NULL, NULL),
(789, 'ماهان', 'ماهان', 21, NULL, NULL, NULL, NULL, NULL),
(790, 'محمدآباد', 'کرمان-محمدآباد', 21, NULL, NULL, NULL, NULL, NULL),
(791, 'محی آباد', 'محی-آباد', 21, NULL, NULL, NULL, NULL, NULL),
(792, 'مردهک', 'مردهک', 21, NULL, NULL, NULL, NULL, NULL),
(793, 'مس سرچشمه', 'مس-سرچشمه', 21, NULL, NULL, NULL, NULL, NULL),
(794, 'منوجان', 'منوجان', 21, NULL, NULL, NULL, NULL, NULL),
(795, 'نجف شهر', 'نجف-شهر', 21, NULL, NULL, NULL, NULL, NULL),
(796, 'نرماشیر', 'نرماشیر', 21, NULL, NULL, NULL, NULL, NULL),
(797, 'نظام شهر', 'نظام-شهر', 21, NULL, NULL, NULL, NULL, NULL),
(798, 'نگار', 'نگار', 21, NULL, NULL, NULL, NULL, NULL),
(799, 'نودژ', 'نودژ', 21, NULL, NULL, NULL, NULL, NULL),
(800, 'هجدک', 'هجدک', 21, NULL, NULL, NULL, NULL, NULL),
(801, 'یزدان شهر', 'یزدان-شهر', 21, NULL, NULL, NULL, NULL, NULL),
(802, 'ازگله', 'ازگله', 22, NULL, NULL, NULL, NULL, NULL),
(803, 'اسلام آباد غرب', 'اسلام-آباد-غرب', 22, NULL, NULL, NULL, NULL, NULL),
(804, 'باینگان', 'باینگان', 22, NULL, NULL, NULL, NULL, NULL),
(805, 'بیستون', 'بیستون', 22, NULL, NULL, NULL, NULL, NULL),
(806, 'پاوه', 'پاوه', 22, NULL, NULL, NULL, NULL, NULL),
(807, 'تازه آباد', 'تازه-آباد', 22, NULL, NULL, NULL, NULL, NULL),
(808, 'جوان رود', 'جوان-رود', 22, NULL, NULL, NULL, NULL, NULL),
(809, 'حمیل', 'حمیل', 22, NULL, NULL, NULL, NULL, NULL),
(810, 'ماهیدشت', 'ماهیدشت', 22, NULL, NULL, NULL, NULL, NULL),
(811, 'روانسر', 'روانسر', 22, NULL, NULL, NULL, NULL, NULL),
(812, 'سرپل ذهاب', 'سرپل-ذهاب', 22, NULL, NULL, NULL, NULL, NULL),
(813, 'سرمست', 'سرمست', 22, NULL, NULL, NULL, NULL, NULL),
(814, 'سطر', 'سطر', 22, NULL, NULL, NULL, NULL, NULL),
(815, 'سنقر', 'سنقر', 22, NULL, NULL, NULL, NULL, NULL),
(816, 'سومار', 'سومار', 22, NULL, NULL, NULL, NULL, NULL),
(817, 'شاهو', 'شاهو', 22, NULL, NULL, NULL, NULL, NULL),
(818, 'صحنه', 'صحنه', 22, NULL, NULL, NULL, NULL, NULL),
(819, 'قصرشیرین', 'قصرشیرین', 22, NULL, NULL, NULL, NULL, NULL),
(820, 'کرمانشاه', 'کرمانشاه', 22, NULL, NULL, NULL, NULL, NULL),
(821, 'کرندغرب', 'کرندغرب', 22, NULL, NULL, NULL, NULL, NULL),
(822, 'کنگاور', 'کنگاور', 22, NULL, NULL, NULL, NULL, NULL),
(823, 'کوزران', 'کوزران', 22, NULL, NULL, NULL, NULL, NULL),
(824, 'گهواره', 'گهواره', 22, NULL, NULL, NULL, NULL, NULL),
(825, 'گیلانغرب', 'گیلانغرب', 22, NULL, NULL, NULL, NULL, NULL),
(826, 'میان راهان', 'میان-راهان', 22, NULL, NULL, NULL, NULL, NULL),
(827, 'نودشه', 'نودشه', 22, NULL, NULL, NULL, NULL, NULL),
(828, 'نوسود', 'نوسود', 22, NULL, NULL, NULL, NULL, NULL),
(829, 'هرسین', 'هرسین', 22, NULL, NULL, NULL, NULL, NULL),
(830, 'هلشی', 'هلشی', 22, NULL, NULL, NULL, NULL, NULL),
(831, 'باشت', 'باشت', 23, NULL, NULL, NULL, NULL, NULL),
(832, 'پاتاوه', 'پاتاوه', 23, NULL, NULL, NULL, NULL, NULL),
(833, 'چرام', 'چرام', 23, NULL, NULL, NULL, NULL, NULL),
(834, 'چیتاب', 'چیتاب', 23, NULL, NULL, NULL, NULL, NULL),
(835, 'دهدشت', 'دهدشت', 23, NULL, NULL, NULL, NULL, NULL),
(836, 'دوگنبدان', 'دوگنبدان', 23, NULL, NULL, NULL, NULL, NULL),
(837, 'دیشموک', 'دیشموک', 23, NULL, NULL, NULL, NULL, NULL),
(838, 'سوق', 'سوق', 23, NULL, NULL, NULL, NULL, NULL),
(839, 'سی سخت', 'سی-سخت', 23, NULL, NULL, NULL, NULL, NULL),
(840, 'قلعه رئیسی', 'قلعه-رئیسی', 23, NULL, NULL, NULL, NULL, NULL),
(841, 'گراب سفلی', 'گراب-سفلی', 23, NULL, NULL, NULL, NULL, NULL),
(842, 'لنده', 'لنده', 23, NULL, NULL, NULL, NULL, NULL),
(843, 'لیکک', 'لیکک', 23, NULL, NULL, NULL, NULL, NULL),
(844, 'مادوان', 'مادوان', 23, NULL, NULL, NULL, NULL, NULL),
(845, 'مارگون', 'مارگون', 23, NULL, NULL, NULL, NULL, NULL),
(846, 'یاسوج', 'یاسوج', 23, NULL, NULL, NULL, NULL, NULL),
(847, 'انبارآلوم', 'انبارآلوم', 24, NULL, NULL, NULL, NULL, NULL),
(848, 'اینچه برون', 'اینچه-برون', 24, NULL, NULL, NULL, NULL, NULL),
(849, 'آزادشهر', 'آزادشهر', 24, NULL, NULL, NULL, NULL, NULL),
(850, 'آق قلا', 'آق-قلا', 24, NULL, NULL, NULL, NULL, NULL),
(851, 'بندرترکمن', 'بندرترکمن', 24, NULL, NULL, NULL, NULL, NULL),
(852, 'بندرگز', 'بندرگز', 24, NULL, NULL, NULL, NULL, NULL),
(853, 'جلین', 'جلین', 24, NULL, NULL, NULL, NULL, NULL),
(854, 'خان ببین', 'خان-ببین', 24, NULL, NULL, NULL, NULL, NULL),
(855, 'دلند', 'دلند', 24, NULL, NULL, NULL, NULL, NULL),
(856, 'رامیان', 'رامیان', 24, NULL, NULL, NULL, NULL, NULL),
(857, 'سرخنکلاته', 'سرخنکلاته', 24, NULL, NULL, NULL, NULL, NULL),
(858, 'سیمین شهر', 'سیمین-شهر', 24, NULL, NULL, NULL, NULL, NULL),
(859, 'علی آباد کتول', 'علی-آباد-کتول', 24, NULL, NULL, NULL, NULL, NULL),
(860, 'فاضل آباد', 'فاضل-آباد', 24, NULL, NULL, NULL, NULL, NULL),
(861, 'کردکوی', 'کردکوی', 24, NULL, NULL, NULL, NULL, NULL),
(862, 'کلاله', 'کلاله', 24, NULL, NULL, NULL, NULL, NULL),
(863, 'گالیکش', 'گالیکش', 24, NULL, NULL, NULL, NULL, NULL),
(864, 'گرگان', 'گرگان', 24, NULL, NULL, NULL, NULL, NULL),
(865, 'گمیش تپه', 'گمیش-تپه', 24, NULL, NULL, NULL, NULL, NULL),
(866, 'گنبدکاووس', 'گنبدکاووس', 24, NULL, NULL, NULL, NULL, NULL),
(867, 'مراوه', 'مراوه', 24, NULL, NULL, NULL, NULL, NULL),
(868, 'مینودشت', 'مینودشت', 24, NULL, NULL, NULL, NULL, NULL),
(869, 'نگین شهر', 'نگین-شهر', 24, NULL, NULL, NULL, NULL, NULL),
(870, 'نوده خاندوز', 'نوده-خاندوز', 24, NULL, NULL, NULL, NULL, NULL),
(871, 'نوکنده', 'نوکنده', 24, NULL, NULL, NULL, NULL, NULL),
(872, 'ازنا', 'ازنا', 25, NULL, NULL, NULL, NULL, NULL),
(873, 'اشترینان', 'اشترینان', 25, NULL, NULL, NULL, NULL, NULL),
(874, 'الشتر', 'الشتر', 25, NULL, NULL, NULL, NULL, NULL),
(875, 'الیگودرز', 'الیگودرز', 25, NULL, NULL, NULL, NULL, NULL),
(876, 'بروجرد', 'بروجرد', 25, NULL, NULL, NULL, NULL, NULL),
(877, 'پلدختر', 'پلدختر', 25, NULL, NULL, NULL, NULL, NULL),
(878, 'چالانچولان', 'چالانچولان', 25, NULL, NULL, NULL, NULL, NULL),
(879, 'چغلوندی', 'چغلوندی', 25, NULL, NULL, NULL, NULL, NULL),
(880, 'چقابل', 'چقابل', 25, NULL, NULL, NULL, NULL, NULL),
(881, 'خرم آباد', 'لرستان-خرم-آباد', 25, NULL, NULL, NULL, NULL, NULL),
(882, 'درب گنبد', 'درب-گنبد', 25, NULL, NULL, NULL, NULL, NULL),
(883, 'دورود', 'دورود', 25, NULL, NULL, NULL, NULL, NULL),
(884, 'زاغه', 'زاغه', 25, NULL, NULL, NULL, NULL, NULL),
(885, 'سپیددشت', 'سپیددشت', 25, NULL, NULL, NULL, NULL, NULL),
(886, 'سراب دوره', 'سراب-دوره', 25, NULL, NULL, NULL, NULL, NULL),
(887, 'فیروزآباد', 'لرستان-فیروزآباد', 25, NULL, NULL, NULL, NULL, NULL),
(888, 'کونانی', 'کونانی', 25, NULL, NULL, NULL, NULL, NULL),
(889, 'کوهدشت', 'کوهدشت', 25, NULL, NULL, NULL, NULL, NULL),
(890, 'گراب', 'گراب', 25, NULL, NULL, NULL, NULL, NULL),
(891, 'معمولان', 'معمولان', 25, NULL, NULL, NULL, NULL, NULL),
(892, 'مومن آباد', 'مومن-آباد', 25, NULL, NULL, NULL, NULL, NULL),
(893, 'نورآباد', 'لرستان-نورآباد', 25, NULL, NULL, NULL, NULL, NULL),
(894, 'ویسیان', 'ویسیان', 25, NULL, NULL, NULL, NULL, NULL),
(895, 'احمدسرگوراب', 'احمدسرگوراب', 26, NULL, NULL, NULL, NULL, NULL),
(896, 'اسالم', 'اسالم', 26, NULL, NULL, NULL, NULL, NULL),
(897, 'اطاقور', 'اطاقور', 26, NULL, NULL, NULL, NULL, NULL),
(898, 'املش', 'املش', 26, NULL, NULL, NULL, NULL, NULL),
(899, 'آستارا', 'آستارا', 26, NULL, NULL, NULL, NULL, NULL),
(900, 'آستانه اشرفیه', 'آستانه-اشرفیه', 26, NULL, NULL, NULL, NULL, NULL),
(901, 'بازار جمعه', 'بازار-جمعه', 26, NULL, NULL, NULL, NULL, NULL),
(902, 'بره سر', 'بره-سر', 26, NULL, NULL, NULL, NULL, NULL),
(903, 'بندرانزلی', 'بندرانزلی', 26, NULL, NULL, NULL, NULL, NULL),
(906, 'پره سر', 'پره-سر', 26, NULL, NULL, NULL, NULL, NULL),
(907, 'تالش', 'تالش', 26, NULL, NULL, NULL, NULL, NULL),
(908, 'توتکابن', 'توتکابن', 26, NULL, NULL, NULL, NULL, NULL),
(909, 'جیرنده', 'جیرنده', 26, NULL, NULL, NULL, NULL, NULL),
(910, 'چابکسر', 'چابکسر', 26, NULL, NULL, NULL, NULL, NULL),
(911, 'چاف و چمخاله', 'چاف-و-چمخاله', 26, NULL, NULL, NULL, NULL, NULL),
(912, 'چوبر', 'چوبر', 26, NULL, NULL, NULL, NULL, NULL),
(913, 'حویق', 'حویق', 26, NULL, NULL, NULL, NULL, NULL),
(914, 'خشکبیجار', 'خشکبیجار', 26, NULL, NULL, NULL, NULL, NULL),
(915, 'خمام', 'خمام', 26, NULL, NULL, NULL, NULL, NULL),
(916, 'دیلمان', 'دیلمان', 26, NULL, NULL, NULL, NULL, NULL),
(917, 'رانکوه', 'رانکوه', 26, NULL, NULL, NULL, NULL, NULL),
(918, 'رحیم آباد', 'رحیم-آباد', 26, NULL, NULL, NULL, NULL, NULL),
(919, 'رستم آباد', 'رستم-آباد', 26, NULL, NULL, NULL, NULL, NULL),
(920, 'رشت', 'رشت', 26, NULL, NULL, NULL, NULL, NULL),
(921, 'رضوانشهر', 'گیلان-رضوانشهر', 26, NULL, NULL, NULL, NULL, NULL),
(922, 'رودبار', 'گیلان-رودبار', 26, NULL, NULL, NULL, NULL, NULL),
(923, 'رودبنه', 'رودبنه', 26, NULL, NULL, NULL, NULL, NULL),
(924, 'رودسر', 'رودسر', 26, NULL, NULL, NULL, NULL, NULL),
(925, 'سنگر', 'سنگر', 26, NULL, NULL, NULL, NULL, NULL),
(926, 'سیاهکل', 'سیاهکل', 26, NULL, NULL, NULL, NULL, NULL),
(927, 'شفت', 'شفت', 26, NULL, NULL, NULL, NULL, NULL),
(928, 'شلمان', 'شلمان', 26, NULL, NULL, NULL, NULL, NULL),
(929, 'صومعه سرا', 'صومعه-سرا', 26, NULL, NULL, NULL, NULL, NULL),
(930, 'فومن', 'فومن', 26, NULL, NULL, NULL, NULL, NULL),
(931, 'کلاچای', 'کلاچای', 26, NULL, NULL, NULL, NULL, NULL),
(932, 'کوچصفهان', 'کوچصفهان', 26, NULL, NULL, NULL, NULL, NULL),
(933, 'کومله', 'کومله', 26, NULL, NULL, NULL, NULL, NULL),
(934, 'کیاشهر', 'کیاشهر', 26, NULL, NULL, NULL, NULL, NULL),
(935, 'گوراب زرمیخ', 'گوراب-زرمیخ', 26, NULL, NULL, NULL, NULL, NULL),
(936, 'لاهیجان', 'لاهیجان', 26, NULL, NULL, NULL, NULL, NULL),
(937, 'لشت نشا', 'لشت-نشا', 26, NULL, NULL, NULL, NULL, NULL),
(938, 'لنگرود', 'لنگرود', 26, NULL, NULL, NULL, NULL, NULL),
(939, 'لوشان', 'لوشان', 26, NULL, NULL, NULL, NULL, NULL),
(940, 'لولمان', 'لولمان', 26, NULL, NULL, NULL, NULL, NULL),
(941, 'لوندویل', 'لوندویل', 26, NULL, NULL, NULL, NULL, NULL),
(942, 'لیسار', 'لیسار', 26, NULL, NULL, NULL, NULL, NULL),
(943, 'ماسال', 'ماسال', 26, NULL, NULL, NULL, NULL, NULL),
(944, 'ماسوله', 'ماسوله', 26, NULL, NULL, NULL, NULL, NULL),
(945, 'مرجقل', 'مرجقل', 26, NULL, NULL, NULL, NULL, NULL),
(946, 'منجیل', 'منجیل', 26, NULL, NULL, NULL, NULL, NULL),
(947, 'واجارگاه', 'واجارگاه', 26, NULL, NULL, NULL, NULL, NULL),
(948, 'امیرکلا', 'امیرکلا', 27, NULL, NULL, NULL, NULL, NULL),
(949, 'ایزدشهر', 'ایزدشهر', 27, NULL, NULL, NULL, NULL, NULL),
(950, 'آلاشت', 'آلاشت', 27, NULL, NULL, NULL, NULL, NULL),
(951, 'آمل', 'آمل', 27, NULL, NULL, NULL, NULL, NULL),
(952, 'بابل', 'بابل', 27, NULL, NULL, NULL, NULL, NULL),
(953, 'بابلسر', 'بابلسر', 27, NULL, NULL, NULL, NULL, NULL),
(954, 'بلده', 'مازندران-بلده', 27, NULL, NULL, NULL, NULL, NULL),
(955, 'بهشهر', 'بهشهر', 27, NULL, NULL, NULL, NULL, NULL),
(956, 'بهنمیر', 'بهنمیر', 27, NULL, NULL, NULL, NULL, NULL),
(957, 'پل سفید', 'پل-سفید', 27, NULL, NULL, NULL, NULL, NULL),
(958, 'تنکابن', 'تنکابن', 27, NULL, NULL, NULL, NULL, NULL),
(959, 'جویبار', 'جویبار', 27, NULL, NULL, NULL, NULL, NULL),
(960, 'چالوس', 'چالوس', 27, NULL, NULL, NULL, NULL, NULL),
(961, 'چمستان', 'چمستان', 27, NULL, NULL, NULL, NULL, NULL),
(962, 'خرم آباد', 'مازندران-خرم-آباد', 27, NULL, NULL, NULL, NULL, NULL),
(963, 'خلیل شهر', 'خلیل-شهر', 27, NULL, NULL, NULL, NULL, NULL),
(964, 'خوش رودپی', 'خوش-رودپی', 27, NULL, NULL, NULL, NULL, NULL),
(965, 'دابودشت', 'دابودشت', 27, NULL, NULL, NULL, NULL, NULL),
(966, 'رامسر', 'رامسر', 27, NULL, NULL, NULL, NULL, NULL),
(967, 'رستمکلا', 'رستمکلا', 27, NULL, NULL, NULL, NULL, NULL),
(968, 'رویان', 'رویان', 27, NULL, NULL, NULL, NULL, NULL),
(969, 'رینه', 'رینه', 27, NULL, NULL, NULL, NULL, NULL),
(970, 'زرگرمحله', 'زرگرمحله', 27, NULL, NULL, NULL, NULL, NULL),
(971, 'زیرآب', 'زیرآب', 27, NULL, NULL, NULL, NULL, NULL),
(972, 'ساری', 'ساری', 27, NULL, NULL, NULL, NULL, NULL),
(973, 'سرخرود', 'سرخرود', 27, NULL, NULL, NULL, NULL, NULL),
(974, 'سلمان شهر', 'سلمان-شهر', 27, NULL, NULL, NULL, NULL, NULL),
(975, 'سورک', 'سورک', 27, NULL, NULL, NULL, NULL, NULL),
(976, 'شیرگاه', 'شیرگاه', 27, NULL, NULL, NULL, NULL, NULL),
(977, 'شیرود', 'شیرود', 27, NULL, NULL, NULL, NULL, NULL),
(978, 'عباس آباد', 'عباس-آباد', 27, NULL, NULL, NULL, NULL, NULL),
(979, 'فریدونکنار', 'فریدونکنار', 27, NULL, NULL, NULL, NULL, NULL),
(980, 'فریم', 'فریم', 27, NULL, NULL, NULL, NULL, NULL),
(981, 'قائم شهر', 'قائم-شهر', 27, NULL, NULL, NULL, NULL, NULL),
(982, 'کتالم', 'کتالم', 27, NULL, NULL, NULL, NULL, NULL),
(983, 'کلارآباد', 'کلارآباد', 27, NULL, NULL, NULL, NULL, NULL),
(984, 'کلاردشت', 'کلاردشت', 27, NULL, NULL, NULL, NULL, NULL),
(985, 'کله بست', 'کله-بست', 27, NULL, NULL, NULL, NULL, NULL),
(986, 'کوهی خیل', 'کوهی-خیل', 27, NULL, NULL, NULL, NULL, NULL),
(987, 'کیاسر', 'کیاسر', 27, NULL, NULL, NULL, NULL, NULL),
(988, 'کیاکلا', 'کیاکلا', 27, NULL, NULL, NULL, NULL, NULL),
(989, 'گتاب', 'گتاب', 27, NULL, NULL, NULL, NULL, NULL),
(990, 'گزنک', 'گزنک', 27, NULL, NULL, NULL, NULL, NULL),
(991, 'گلوگاه', 'گلوگاه', 27, NULL, NULL, NULL, NULL, NULL),
(992, 'محمودآباد', 'مازندران-محمودآباد', 27, NULL, NULL, NULL, NULL, NULL),
(993, 'مرزن آباد', 'مرزن-آباد', 27, NULL, NULL, NULL, NULL, NULL),
(994, 'مرزیکلا', 'مرزیکلا', 27, NULL, NULL, NULL, NULL, NULL),
(995, 'نشتارود', 'نشتارود', 27, NULL, NULL, NULL, NULL, NULL),
(996, 'نکا', 'نکا', 27, NULL, NULL, NULL, NULL, NULL),
(997, 'نور', 'نور', 27, NULL, NULL, NULL, NULL, NULL),
(998, 'نوشهر', 'نوشهر', 27, NULL, NULL, NULL, NULL, NULL),
(999, 'اراک', 'اراک', 28, NULL, NULL, NULL, NULL, NULL),
(1000, 'آستانه', 'آستانه', 28, NULL, NULL, NULL, NULL, NULL),
(1001, 'آشتیان', 'آشتیان', 28, NULL, NULL, NULL, NULL, NULL),
(1002, 'پرندک', 'پرندک', 28, NULL, NULL, NULL, NULL, NULL),
(1003, 'تفرش', 'تفرش', 28, NULL, NULL, NULL, NULL, NULL),
(1004, 'توره', 'توره', 28, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `cities` (`id`, `name`, `slug`, `province_id`, `created_at`, `deleted_at`, `updated_at`, `latitude`, `longitude`) VALUES
(1005, 'جاورسیان', 'جاورسیان', 28, NULL, NULL, NULL, NULL, NULL),
(1006, 'خشکرود', 'خشکرود', 28, NULL, NULL, NULL, NULL, NULL),
(1007, 'خمین', 'خمین', 28, NULL, NULL, NULL, NULL, NULL),
(1008, 'خنداب', 'خنداب', 28, NULL, NULL, NULL, NULL, NULL),
(1009, 'داودآباد', 'داودآباد', 28, NULL, NULL, NULL, NULL, NULL),
(1010, 'دلیجان', 'دلیجان', 28, NULL, NULL, NULL, NULL, NULL),
(1011, 'رازقان', 'رازقان', 28, NULL, NULL, NULL, NULL, NULL),
(1012, 'زاویه', 'زاویه', 28, NULL, NULL, NULL, NULL, NULL),
(1013, 'ساروق', 'ساروق', 28, NULL, NULL, NULL, NULL, NULL),
(1014, 'ساوه', 'ساوه', 28, NULL, NULL, NULL, NULL, NULL),
(1015, 'سنجان', 'سنجان', 28, NULL, NULL, NULL, NULL, NULL),
(1016, 'شازند', 'شازند', 28, NULL, NULL, NULL, NULL, NULL),
(1017, 'غرق آباد', 'غرق-آباد', 28, NULL, NULL, NULL, NULL, NULL),
(1018, 'فرمهین', 'فرمهین', 28, NULL, NULL, NULL, NULL, NULL),
(1019, 'قورچی باشی', 'قورچی-باشی', 28, NULL, NULL, NULL, NULL, NULL),
(1020, 'کرهرود', 'کرهرود', 28, NULL, NULL, NULL, NULL, NULL),
(1021, 'کمیجان', 'کمیجان', 28, NULL, NULL, NULL, NULL, NULL),
(1022, 'مامونیه', 'مامونیه', 28, NULL, NULL, NULL, NULL, NULL),
(1023, 'محلات', 'محلات', 28, NULL, NULL, NULL, NULL, NULL),
(1024, 'مهاجران', 'مهاجران', 28, NULL, NULL, NULL, NULL, NULL),
(1025, 'میلاجرد', 'میلاجرد', 28, NULL, NULL, NULL, NULL, NULL),
(1026, 'نراق', 'نراق', 28, NULL, NULL, NULL, NULL, NULL),
(1027, 'نوبران', 'نوبران', 28, NULL, NULL, NULL, NULL, NULL),
(1028, 'نیمور', 'نیمور', 28, NULL, NULL, NULL, NULL, NULL),
(1029, 'هندودر', 'هندودر', 28, NULL, NULL, NULL, NULL, NULL),
(1030, 'ابوموسی', 'ابوموسی', 29, NULL, NULL, NULL, NULL, NULL),
(1031, 'بستک', 'بستک', 29, NULL, NULL, NULL, NULL, NULL),
(1032, 'بندرجاسک', 'بندرجاسک', 29, NULL, NULL, NULL, NULL, NULL),
(1033, 'بندرچارک', 'بندرچارک', 29, NULL, NULL, NULL, NULL, NULL),
(1034, 'بندرخمیر', 'بندرخمیر', 29, NULL, NULL, NULL, NULL, NULL),
(1035, 'بندرعباس', 'بندرعباس', 29, NULL, NULL, NULL, NULL, NULL),
(1036, 'بندرلنگه', 'بندرلنگه', 29, NULL, NULL, NULL, NULL, NULL),
(1037, 'بیکا', 'بیکا', 29, NULL, NULL, NULL, NULL, NULL),
(1038, 'پارسیان', 'پارسیان', 29, NULL, NULL, NULL, NULL, NULL),
(1039, 'تخت', 'تخت', 29, NULL, NULL, NULL, NULL, NULL),
(1040, 'جناح', 'جناح', 29, NULL, NULL, NULL, NULL, NULL),
(1041, 'حاجی آباد', 'هرمزگان-حاجی-آباد', 29, NULL, NULL, NULL, NULL, NULL),
(1042, 'درگهان', 'درگهان', 29, NULL, NULL, NULL, NULL, NULL),
(1043, 'دهبارز', 'دهبارز', 29, NULL, NULL, NULL, NULL, NULL),
(1044, 'رویدر', 'رویدر', 29, NULL, NULL, NULL, NULL, NULL),
(1045, 'زیارتعلی', 'زیارتعلی', 29, NULL, NULL, NULL, NULL, NULL),
(1046, 'سردشت', 'هرمزگان-سردشت', 29, NULL, NULL, NULL, NULL, NULL),
(1047, 'سندرک', 'سندرک', 29, NULL, NULL, NULL, NULL, NULL),
(1048, 'سوزا', 'سوزا', 29, NULL, NULL, NULL, NULL, NULL),
(1049, 'سیریک', 'سیریک', 29, NULL, NULL, NULL, NULL, NULL),
(1050, 'فارغان', 'فارغان', 29, NULL, NULL, NULL, NULL, NULL),
(1051, 'فین', 'فین', 29, NULL, NULL, NULL, NULL, NULL),
(1052, 'قشم', 'قشم', 29, NULL, NULL, NULL, NULL, NULL),
(1053, 'قلعه قاضی', 'قلعه-قاضی', 29, NULL, NULL, NULL, NULL, NULL),
(1054, 'کنگ', 'کنگ', 29, NULL, NULL, NULL, NULL, NULL),
(1055, 'کوشکنار', 'کوشکنار', 29, NULL, NULL, NULL, NULL, NULL),
(1056, 'کیش', 'کیش', 29, NULL, NULL, NULL, NULL, NULL),
(1057, 'گوهران', 'گوهران', 29, NULL, NULL, NULL, NULL, NULL),
(1058, 'میناب', 'میناب', 29, NULL, NULL, NULL, NULL, NULL),
(1059, 'هرمز', 'هرمز', 29, NULL, NULL, NULL, NULL, NULL),
(1060, 'هشتبندی', 'هشتبندی', 29, NULL, NULL, NULL, NULL, NULL),
(1061, 'ازندریان', 'ازندریان', 30, NULL, NULL, NULL, NULL, NULL),
(1062, 'اسدآباد', 'اسدآباد', 30, NULL, NULL, NULL, NULL, NULL),
(1063, 'برزول', 'برزول', 30, NULL, NULL, NULL, NULL, NULL),
(1064, 'بهار', 'بهار', 30, NULL, NULL, NULL, NULL, NULL),
(1065, 'تویسرکان', 'تویسرکان', 30, NULL, NULL, NULL, NULL, NULL),
(1066, 'جورقان', 'جورقان', 30, NULL, NULL, NULL, NULL, NULL),
(1067, 'جوکار', 'جوکار', 30, NULL, NULL, NULL, NULL, NULL),
(1068, 'دمق', 'دمق', 30, NULL, NULL, NULL, NULL, NULL),
(1069, 'رزن', 'رزن', 30, NULL, NULL, NULL, NULL, NULL),
(1070, 'زنگنه', 'زنگنه', 30, NULL, NULL, NULL, NULL, NULL),
(1071, 'سامن', 'سامن', 30, NULL, NULL, NULL, NULL, NULL),
(1072, 'سرکان', 'سرکان', 30, NULL, NULL, NULL, NULL, NULL),
(1073, 'شیرین سو', 'شیرین-سو', 30, NULL, NULL, NULL, NULL, NULL),
(1074, 'صالح آباد', 'همدان-صالح-آباد', 30, NULL, NULL, NULL, NULL, NULL),
(1075, 'فامنین', 'فامنین', 30, NULL, NULL, NULL, NULL, NULL),
(1076, 'فرسفج', 'فرسفج', 30, NULL, NULL, NULL, NULL, NULL),
(1077, 'فیروزان', 'فیروزان', 30, NULL, NULL, NULL, NULL, NULL),
(1078, 'قروه درجزین', 'قروه-درجزین', 30, NULL, NULL, NULL, NULL, NULL),
(1079, 'قهاوند', 'قهاوند', 30, NULL, NULL, NULL, NULL, NULL),
(1080, 'کبودر آهنگ', 'کبودر-آهنگ', 30, NULL, NULL, NULL, NULL, NULL),
(1081, 'گل تپه', 'گل-تپه', 30, NULL, NULL, NULL, NULL, NULL),
(1082, 'گیان', 'گیان', 30, NULL, NULL, NULL, NULL, NULL),
(1083, 'لالجین', 'لالجین', 30, NULL, NULL, NULL, NULL, NULL),
(1084, 'مریانج', 'مریانج', 30, NULL, NULL, NULL, NULL, NULL),
(1085, 'ملایر', 'ملایر', 30, NULL, NULL, NULL, NULL, NULL),
(1086, 'نهاوند', 'نهاوند', 30, NULL, NULL, NULL, NULL, NULL),
(1087, 'همدان', 'همدان', 30, NULL, NULL, NULL, NULL, NULL),
(1088, 'ابرکوه', 'ابرکوه', 31, NULL, NULL, NULL, NULL, NULL),
(1089, 'احمدآباد', 'احمدآباد', 31, NULL, NULL, NULL, NULL, NULL),
(1090, 'اردکان', 'یزد-اردکان', 31, NULL, NULL, NULL, NULL, NULL),
(1091, 'اشکذر', 'اشکذر', 31, NULL, NULL, NULL, NULL, NULL),
(1092, 'بافق', 'بافق', 31, NULL, NULL, NULL, NULL, NULL),
(1093, 'بفروئیه', 'بفروئیه', 31, NULL, NULL, NULL, NULL, NULL),
(1094, 'بهاباد', 'بهاباد', 31, NULL, NULL, NULL, NULL, NULL),
(1095, 'تفت', 'تفت', 31, NULL, NULL, NULL, NULL, NULL),
(1096, 'حمیدیا', 'حمیدیا', 31, NULL, NULL, NULL, NULL, NULL),
(1097, 'خضرآباد', 'خضرآباد', 31, NULL, NULL, NULL, NULL, NULL),
(1098, 'دیهوک', 'دیهوک', 31, NULL, NULL, NULL, NULL, NULL),
(1099, 'زارچ', 'زارچ', 31, NULL, NULL, NULL, NULL, NULL),
(1100, 'شاهدیه', 'شاهدیه', 31, NULL, NULL, NULL, NULL, NULL),
(1101, 'طبس', 'یزد-طبس', 31, NULL, NULL, NULL, NULL, NULL),
(1103, 'عقدا', 'عقدا', 31, NULL, NULL, NULL, NULL, NULL),
(1104, 'مروست', 'مروست', 31, NULL, NULL, NULL, NULL, NULL),
(1105, 'مهردشت', 'مهردشت', 31, NULL, NULL, NULL, NULL, NULL),
(1106, 'مهریز', 'مهریز', 31, NULL, NULL, NULL, NULL, NULL),
(1107, 'میبد', 'میبد', 31, NULL, NULL, NULL, NULL, NULL),
(1108, 'ندوشن', 'ندوشن', 31, NULL, NULL, NULL, NULL, NULL),
(1109, 'نیر', 'یزد-نیر', 31, NULL, NULL, NULL, NULL, NULL),
(1110, 'هرات', 'هرات', 31, NULL, NULL, NULL, NULL, NULL),
(1111, 'یزد', 'یزد', 31, NULL, NULL, NULL, NULL, NULL),
(1116, 'پرند', 'پرند', 8, NULL, NULL, NULL, NULL, NULL),
(1117, 'فردیس', 'فردیس', 5, NULL, NULL, NULL, NULL, NULL),
(1118, 'مارلیک', 'مارلیک', 5, NULL, NULL, NULL, NULL, NULL),
(1119, 'سادات شهر', 'سادات-شهر', 27, NULL, NULL, NULL, NULL, NULL),
(1121, 'زیباکنار', 'زیباکنار', 26, NULL, NULL, NULL, NULL, NULL),
(1135, 'کردان', 'کردان', 5, NULL, NULL, NULL, NULL, NULL),
(1137, 'ساوجبلاغ', 'ساوجبلاغ', 5, NULL, NULL, NULL, NULL, NULL),
(1138, 'تهران دشت', 'تهران-دشت', 5, NULL, NULL, NULL, NULL, NULL),
(1150, 'گلبهار', 'گلبهار', 11, NULL, NULL, NULL, NULL, NULL),
(1153, 'قیامدشت', 'قیامدشت', 8, NULL, NULL, NULL, NULL, NULL),
(1155, 'بینالود', 'بینالود', 11, NULL, NULL, NULL, NULL, NULL),
(1159, 'پیربازار', 'پیربازار', 26, NULL, NULL, NULL, NULL, NULL),
(1160, 'رضوانشهر', 'رضوانشهر', 31, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `provinces` (`id`, `name`, `slug`, `created_at`, `updated_at`, `deleted_at`, `latitude`, `longitude`) VALUES
(1, 'آذربایجان شرقی', 'آذربایجان-شرقی', NULL, NULL, NULL, NULL, NULL),
(2, 'آذربایجان غربی', 'آذربایجان-غربی', NULL, NULL, NULL, NULL, NULL),
(3, 'اردبیل', 'اردبیل', NULL, NULL, NULL, NULL, NULL),
(4, 'اصفهان', 'اصفهان', NULL, NULL, NULL, NULL, NULL),
(5, 'البرز', 'البرز', NULL, NULL, NULL, NULL, NULL),
(6, 'ایلام', 'ایلام', NULL, NULL, NULL, NULL, NULL),
(7, 'بوشهر', 'بوشهر', NULL, NULL, NULL, NULL, NULL),
(8, 'تهران', 'تهران', NULL, NULL, NULL, NULL, NULL),
(9, 'چهارمحال و بختیاری', 'چهارمحال-بختیاری', NULL, NULL, NULL, NULL, NULL),
(10, 'خراسان جنوبی', 'خراسان-جنوبی', NULL, NULL, NULL, NULL, NULL),
(11, 'خراسان رضوی', 'خراسان-رضوی', NULL, NULL, NULL, NULL, NULL),
(12, 'خراسان شمالی', 'خراسان-شمالی', NULL, NULL, NULL, NULL, NULL),
(13, 'خوزستان', 'خوزستان', NULL, NULL, NULL, NULL, NULL),
(14, 'زنجان', 'زنجان', NULL, NULL, NULL, NULL, NULL),
(15, 'سمنان', 'سمنان', NULL, NULL, NULL, NULL, NULL),
(16, 'سیستان و بلوچستان', 'سیستان-بلوچستان', NULL, NULL, NULL, NULL, NULL),
(17, 'فارس', 'فارس', NULL, NULL, NULL, NULL, NULL),
(18, 'قزوین', 'قزوین', NULL, NULL, NULL, NULL, NULL),
(19, 'قم', 'قم', NULL, NULL, NULL, NULL, NULL),
(20, 'کردستان', 'کردستان', NULL, NULL, NULL, NULL, NULL),
(21, 'کرمان', 'کرمان', NULL, NULL, NULL, NULL, NULL),
(22, 'کرمانشاه', 'کرمانشاه', NULL, NULL, NULL, NULL, NULL),
(23, 'کهگیلویه و بویراحمد', 'کهگیلویه-بویراحمد', NULL, NULL, NULL, NULL, NULL),
(24, 'گلستان', 'گلستان', NULL, NULL, NULL, NULL, NULL),
(25, 'لرستان', 'لرستان', NULL, NULL, NULL, NULL, NULL),
(26, 'گیلان', 'گیلان', NULL, NULL, NULL, NULL, NULL),
(27, 'مازندران', 'مازندران', NULL, NULL, NULL, NULL, NULL),
(28, 'مرکزی', 'مرکزی', NULL, NULL, NULL, NULL, NULL),
(29, 'هرمزگان', 'هرمزگان', NULL, NULL, NULL, NULL, NULL),
(30, 'همدان', 'همدان', NULL, NULL, NULL, NULL, NULL),
(31, 'یزد', 'یزد', NULL, NULL, NULL, NULL, NULL);



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;